"""Stage 7.4 evidence:

- Current public game state summary
- Active phase and timing window
- Legal actions generated by the backend
- Negotiation context
- Active contracts and obligations
- Relevant memory snippets
- Relevant rule snippets
- Personality profile
- Required output schema and instruction contract
- Prompt context is recorded for audit
- Context packs expose no other player's private memory
- Public negotiation messages, public deals, public contracts, and public game state remain visible
- AI context pack builder uses backend legal-action generation
- public game summary excludes hidden deck/RNG internals
- memory visibility rules prevent other players' private memory from leaking
- prompt context packs are persisted unchanged by the Stage 7.3 orchestrator
"""

from __future__ import annotations

import json
import os
from collections.abc import AsyncIterator, Sequence
from pathlib import Path
from typing import Any
from uuid import UUID

import pytest
import pytest_asyncio
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker, create_async_engine

from app.ai.context_pack import build_ai_context_pack, build_ai_context_pack_from_db
from app.ai.orchestrator import (
    CodexExecAIDecisionRequest,
    CodexExecProcessResult,
    CodexExecRunner,
    request_codex_ai_decision,
)
from app.db.metadata import (
    ai_decisions,
    ai_memory_entries,
    ai_profiles,
    contracts,
    deals,
    game_events,
    games,
    metadata,
    negotiation_messages,
    negotiations,
    obligations,
    players,
)
from app.rules.actions import list_legal_actions
from app.rules.phases import TurnPhase
from app.rules.state import GameState, PlayerSetup, create_initial_game_state


TEST_DATABASE_URL = os.getenv(
    "MONOPOLY_TEST_DATABASE_URL",
    "postgresql+asyncpg://monopoly:monopoly@127.0.0.1:5432/monopoly_ai_game",
)

GAME_ID = UUID("00000000-0000-0000-0000-000000007401")
AI_PLAYER_ID = UUID("00000000-0000-0000-0000-000000007402")
OTHER_PLAYER_ID = UUID("00000000-0000-0000-0000-000000007403")
AI_PROFILE_ID = UUID("00000000-0000-0000-0000-000000007404")
NEGOTIATION_ID = UUID("00000000-0000-0000-0000-000000007405")
DEAL_ID = UUID("00000000-0000-0000-0000-000000007406")
CONTRACT_ID = UUID("00000000-0000-0000-0000-000000007407")
OBLIGATION_ID = UUID("00000000-0000-0000-0000-000000007408")
THIRD_PLAYER_ID = UUID("00000000-0000-0000-0000-000000007409")
OWN_MEMORY_DECISION_ID = UUID("00000000-0000-0000-0000-000000007410")
OTHER_PRIVATE_MEMORY_DECISION_ID = UUID("00000000-0000-0000-0000-000000007411")
TABLE_MEMORY_DECISION_ID = UUID("00000000-0000-0000-0000-000000007412")


class FakeCodexRunner(CodexExecRunner):
    def __init__(self, final_output: dict[str, Any]) -> None:
        self.final_output = final_output
        self.calls: list[dict[str, Any]] = []

    def run(
        self,
        command: Sequence[str],
        *,
        stdin: str,
        timeout_seconds: float,
        output_last_message_path: Path | None,
    ) -> CodexExecProcessResult:
        self.calls.append(
            {
                "command": list(command),
                "stdin": stdin,
                "timeout_seconds": timeout_seconds,
                "output_last_message_path": output_last_message_path,
            }
        )
        if output_last_message_path is not None:
            output_last_message_path.parent.mkdir(parents=True, exist_ok=True)
            output_last_message_path.write_text(json.dumps(self.final_output), encoding="utf-8")
        return CodexExecProcessResult(
            returncode=0,
            stdout="\n".join(
                [
                    json.dumps({"type": "session_configured", "model": "codex"}),
                    json.dumps(
                        {
                            "type": "item_completed",
                            "item": {
                                "type": "message",
                                "role": "assistant",
                                "content": [
                                    {
                                        "type": "output_text",
                                        "text": json.dumps(self.final_output),
                                    }
                                ],
                            },
                        }
                    ),
                ]
            ),
            stderr="",
        )


@pytest_asyncio.fixture
async def engine() -> AsyncIterator[AsyncEngine]:
    engine = create_async_engine(TEST_DATABASE_URL, pool_pre_ping=True)
    async with engine.begin() as connection:
        await connection.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
        await connection.run_sync(metadata.create_all)

    try:
        yield engine
    finally:
        await engine.dispose()


@pytest_asyncio.fixture
async def session_factory(engine: AsyncEngine) -> async_sessionmaker:
    return async_sessionmaker(bind=engine, expire_on_commit=False)


def _state() -> GameState:
    return create_initial_game_state(
        seed="phase-7-stage-7.4-context-pack",
        game_id=str(GAME_ID),
        players=(
            PlayerSetup(id=str(AI_PLAYER_ID), name="Grace", kind="ai"),
            PlayerSetup(id=str(OTHER_PLAYER_ID), name="Ada", kind="human"),
            PlayerSetup(id=str(THIRD_PLAYER_ID), name="Lin", kind="ai"),
        ),
    )


def test_context_pack_uses_legal_actions_and_hides_private_engine_state() -> None:
    state = _state()
    pack = build_ai_context_pack(
        state,
        player_id=AI_PLAYER_ID,
        ai_profile={
            "id": AI_PROFILE_ID,
            "persona_name": "Test Persona",
            "persona_summary": {"summary": "A deterministic auction-aware AI."},
            "strategy_profile": {"risk_tolerance": 0.4, "cooperation": 0.7},
        },
        memory_snippets=[
            {
                "id": "own-private",
                "player_id": str(AI_PLAYER_ID),
                "visibility": "private",
                "category": "strategic_belief",
                "content": "Keep cash available for early auctions.",
                "importance": 8,
            },
            {
                "id": "other-private",
                "player_id": str(OTHER_PLAYER_ID),
                "visibility": "private",
                "category": "player_trust_model",
                "content": "Ada secretly wants the orange group.",
                "importance": 9,
            },
            {
                "id": "table-visible",
                "player_id": str(OTHER_PLAYER_ID),
                "visibility": "table",
                "category": "deal_history",
                "content": "Ada publicly rejected a railroad package.",
                "importance": 5,
            },
        ],
        rule_snippets=[
            {
                "id": "legal-actions-authority",
                "source": "backend",
                "text": "Choose only from backend-generated legal actions.",
            }
        ],
    )

    assert pack["context_pack_schema_version"] == "ai-context-pack-v1"
    assert pack["public_game_state"]["state_hash"] == state.state_hash()
    assert pack["public_game_state"]["event_sequence"] == state.event_sequence
    assert pack["timing"]["active_phase"] == "START_TURN"
    assert pack["legal_actions"] == [
        action.model_dump(mode="json") for action in list_legal_actions(state, str(AI_PLAYER_ID))
    ]
    assert "required_output_schema" not in pack
    assert pack["instruction_contract"]["backend_is_rules_authority"] is True
    assert pack["instruction_contract"]["no_emergency_action_path"] is True

    serialized_public_state = json.dumps(pack["public_game_state"], sort_keys=True)
    assert "rng" not in serialized_public_state
    assert "seed" not in serialized_public_state
    assert "draw_pile" not in serialized_public_state
    assert "discard_pile" not in serialized_public_state
    assert "decks" not in serialized_public_state

    memory_text = json.dumps(pack["memory"]["snippets"], sort_keys=True)
    assert "Keep cash available for early auctions." in memory_text
    assert "Ada publicly rejected a railroad package." in memory_text
    assert "Ada secretly wants the orange group." not in memory_text


def test_context_pack_prioritizes_legal_monopoly_development_before_roll() -> None:
    state = _state_with_orange_monopoly()
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    build_actions = [action for action in pack["legal_actions"] if action["type"] == "BUY_HOUSE"]
    assert len(build_actions) == 3

    guidance = pack["action_selection_guidance"]
    assert guidance["recommended_action_types_before_roll"] == ["BUY_HOUSE"]
    assert guidance["lower_priority_action_types"] == ["ROLL_DICE", "MORTGAGE_PROPERTY"]
    assert [opportunity["property_id"] for opportunity in guidance["development_opportunities"]] == [
        "property_st_james_place",
        "property_tennessee_avenue",
        "property_new_york_avenue",
    ]
    assert all(opportunity["cash_after_cost"] == 2900 for opportunity in guidance["development_opportunities"])
    assert "complete color group" in guidance["turn_guidance"][0]
    assert any("BUY_HOUSE" in instruction for instruction in pack["instruction_contract"]["instructions"])


def test_context_pack_surfaces_near_monopoly_trade_opportunities() -> None:
    state = _state_with_orange_near_monopoly()
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID, decision_type="open_negotiation")

    guidance = pack["negotiation_strategy_guidance"]

    assert guidance["recommended_decision_types"] == ["open_negotiation"]
    assert guidance["open_negotiation_payload_template"] == {
        "participant_player_ids": [str(AI_PLAYER_ID), str(OTHER_PLAYER_ID)],
        "context": {
            "topic": "Trade for Tennessee Avenue to complete Orange",
            "target_property_id": "property_tennessee_avenue",
            "target_property_name": "Tennessee Avenue",
            "target_owner_id": str(OTHER_PLAYER_ID),
            "target_owner_name": "Ada",
            "strategic_reason": (
                "Completing Orange unlocks BUY_HOUSE development and materially raises rent pressure."
            ),
            "suggested_offer": {
                "cash_budget_floor": 180,
                "cash_budget_ceiling": 270,
                "avoid_trading_away_group_property_ids": [
                    "property_st_james_place",
                    "property_new_york_avenue",
                ],
            },
        },
    }
    assert guidance["trade_opportunities"] == [
        {
            "kind": "complete_street_group",
            "priority": "high",
            "group": "orange",
            "group_name": "Orange",
            "actor_owned_property_ids": [
                "property_st_james_place",
                "property_new_york_avenue",
            ],
            "actor_owned_property_names": [
                "St. James Place",
                "New York Avenue",
            ],
            "target_property_id": "property_tennessee_avenue",
            "target_property_name": "Tennessee Avenue",
            "target_owner_id": str(OTHER_PLAYER_ID),
            "target_owner_name": "Ada",
            "participants": [str(AI_PLAYER_ID), str(OTHER_PLAYER_ID)],
            "strategic_reason": (
                "Completing Orange unlocks BUY_HOUSE development and materially raises rent pressure."
            ),
            "suggested_offer": {
                "cash_budget_floor": 180,
                "cash_budget_ceiling": 270,
                "avoid_trading_away_group_property_ids": [
                    "property_st_james_place",
                    "property_new_york_avenue",
                ],
            },
        }
    ]
    instruction_text = " ".join(pack["instruction_contract"]["instructions"])
    assert "open_negotiation" in instruction_text
    assert "participant_player_ids must include both this AI player and the target owner" in instruction_text
    assert "open_negotiation.negotiation.context must be a JSON object" in instruction_text


def test_context_pack_instructs_deal_proposals_as_json_structured_deals() -> None:
    state = _state_with_orange_near_monopoly()
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID, decision_type="deal_proposal")

    instruction_text = " ".join(pack["instruction_contract"]["instructions"])

    assert "deal_proposal.deal.terms" in instruction_text
    assert "valid JSON object string" in instruction_text
    assert "Do not prefix" in instruction_text
    assert "structured_deal" in instruction_text
    assert "terms array" in instruction_text


def test_context_pack_deprioritizes_mortgage_when_cash_is_healthy_without_debt() -> None:
    state = _state_with_owned_railroad(cash=900)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    mortgage_actions = [
        action for action in pack["legal_actions"] if action["type"] == "MORTGAGE_PROPERTY"
    ]
    assert len(mortgage_actions) == 1
    assert mortgage_actions[0]["payload"]["property_id"] == "property_b_and_o_railroad"

    guidance = pack["action_selection_guidance"]
    assert "MORTGAGE_PROPERTY" in guidance["lower_priority_action_types"]
    assert guidance["mortgage_guidance"]["recommendation"] == "avoid_unless_debt_or_liquidity_pressure"
    assert guidance["mortgage_guidance"]["has_active_debt"] is False
    assert guidance["mortgage_guidance"]["cash_available"] == 900
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "Avoid MORTGAGE_PROPERTY" in guidance_text
    assert "active debt" in guidance_text
    assert any("MORTGAGE_PROPERTY" in instruction for instruction in pack["instruction_contract"]["instructions"])


def test_context_pack_keeps_mortgage_available_for_active_debt_liquidation() -> None:
    state = _state_with_active_debt_and_owned_railroad(cash=0)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    mortgage_actions = [
        action for action in pack["legal_actions"] if action["type"] == "MORTGAGE_PROPERTY"
    ]
    assert len(mortgage_actions) == 1

    guidance = pack["action_selection_guidance"]
    assert "MORTGAGE_PROPERTY" not in guidance["lower_priority_action_types"]
    assert guidance["mortgage_guidance"]["recommendation"] == "liquidate_only_enough_for_active_debt"
    assert guidance["mortgage_guidance"]["has_active_debt"] is True
    assert guidance["mortgage_guidance"]["cash_available"] == 0
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "active debt" in guidance_text
    assert "only enough" in guidance_text


def test_context_pack_prioritizes_unmortgaging_rent_property_when_cash_stays_healthy() -> None:
    state = _state_with_mortgaged_railroad(cash=900)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    unmortgage_actions = [
        action for action in pack["legal_actions"] if action["type"] == "UNMORTGAGE_PROPERTY"
    ]
    assert len(unmortgage_actions) == 1
    assert unmortgage_actions[0]["payload"]["property_id"] == "property_b_and_o_railroad"
    assert unmortgage_actions[0]["payload"]["cost"] == 110

    guidance = pack["action_selection_guidance"]
    assert "UNMORTGAGE_PROPERTY" in guidance["recommended_action_types_before_roll"]
    assert "ROLL_DICE" in guidance["lower_priority_action_types"]
    assert guidance["unmortgage_guidance"]["recommendation"] == "restore_rent_when_cash_healthy"
    assert guidance["unmortgage_guidance"]["cash_after_cheapest_unmortgage"] == 790
    assert guidance["unmortgage_guidance"]["unmortgageable_property_ids"] == [
        "property_b_and_o_railroad"
    ]
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "UNMORTGAGE_PROPERTY" in guidance_text
    assert "restore rent" in guidance_text
    assert any("UNMORTGAGE_PROPERTY" in instruction for instruction in pack["instruction_contract"]["instructions"])


def test_context_pack_prioritizes_jail_card_over_fine_and_jail_roll() -> None:
    state = _state_with_jail_card(cash=900)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    legal_action_types = {action["type"] for action in pack["legal_actions"]}
    assert {"ROLL_DICE", "PAY_JAIL_FINE", "USE_GET_OUT_OF_JAIL_CARD"}.issubset(legal_action_types)
    card_action = next(action for action in pack["legal_actions"] if action["type"] == "USE_GET_OUT_OF_JAIL_CARD")
    assert card_action["payload"]["card_id"] == "card_community_get_out_of_jail"

    guidance = pack["action_selection_guidance"]
    assert "USE_GET_OUT_OF_JAIL_CARD" in guidance["recommended_action_types_before_roll"]
    assert "PAY_JAIL_FINE" in guidance["lower_priority_action_types"]
    assert "ROLL_DICE" in guidance["lower_priority_action_types"]
    assert guidance["jail_guidance"] == {
        "action_available": True,
        "recommendation": "use_card_before_paying_or_rolling",
        "cash_available": 900,
        "jail_turns": 1,
        "jail_card_ids": ["card_community_get_out_of_jail"],
        "pay_fine_available": True,
        "roll_dice_available": True,
    }
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "USE_GET_OUT_OF_JAIL_CARD" in guidance_text
    assert "PAY_JAIL_FINE" in guidance_text
    assert "ROLL_DICE" in guidance_text
    assert any("USE_GET_OUT_OF_JAIL_CARD" in instruction for instruction in pack["instruction_contract"]["instructions"])


def test_context_pack_prefers_buying_landed_property_when_cash_is_healthy() -> None:
    state = _state_landed_on_unowned_reading_railroad(cash=1500)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    assert any(action["type"] == "BUY_PROPERTY" for action in pack["legal_actions"])
    assert any(action["type"] == "START_AUCTION" for action in pack["legal_actions"])

    guidance = pack["action_selection_guidance"]
    assert guidance["recommended_action_types"] == ["BUY_PROPERTY"]
    assert "START_AUCTION" in guidance["lower_priority_action_types"]
    assert guidance["purchase_guidance"]["recommendation"] == "buy_property_at_list_price"
    assert guidance["purchase_guidance"]["property_id"] == "property_reading_railroad"
    assert guidance["purchase_guidance"]["cash_after_price"] == 1300
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "Prefer BUY_PROPERTY" in guidance_text
    assert "START_AUCTION" in guidance_text
    assert any(
        "BUY_PROPERTY" in instruction and "START_AUCTION" in instruction
        for instruction in pack["instruction_contract"]["instructions"]
    )


def test_context_pack_keeps_auction_viable_when_buying_would_break_liquidity_floor() -> None:
    state = _state_landed_on_unowned_reading_railroad(cash=220)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    guidance = pack["action_selection_guidance"]
    assert "BUY_PROPERTY" not in guidance["recommended_action_types"]
    assert "START_AUCTION" not in guidance["lower_priority_action_types"]
    assert guidance["purchase_guidance"]["recommendation"] == "consider_auction_for_liquidity"
    assert guidance["purchase_guidance"]["cash_after_price"] == 20
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "cash_after_price would fall below" in guidance_text


def test_context_pack_guides_auction_bids_as_deliberate_values_not_minimum_loops() -> None:
    state = _state_with_active_auction()
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    bid_action = next(action for action in pack["legal_actions"] if action["type"] == "BID_AUCTION")
    assert bid_action["payload"]["amount"] == 51
    assert bid_action["schema"]["properties"]["amount"]["minimum"] == 51
    assert bid_action["schema"]["properties"]["amount"]["maximum"] == 1500
    assert "not a recommended bid" in bid_action["description"]

    guidance = pack["action_selection_guidance"]
    assert guidance["auction_guidance"] == {
        "property_id": "property_virginia_avenue",
        "property_name": "Virginia Avenue",
        "property_group": "pink",
        "property_price": 160,
        "current_high_bidder_id": str(OTHER_PLAYER_ID),
        "current_high_bid_amount": 50,
        "minimum_bid": 51,
        "cash_available": 1500,
        "same_group_owned_property_ids": [],
        "property_group_size": 3,
        "completes_property_group": False,
        "valuation_ceiling": 160,
        "valuation_basis": "listed_price",
        "pass_action_available": True,
        "bid_payload_amount_is_floor": True,
    }
    guidance_text = " ".join(guidance["turn_guidance"])
    assert "not a recommendation" in guidance_text
    assert "one-dollar increment loops" in guidance_text
    assert "valuation ceiling" in guidance_text


def test_context_pack_guides_auction_pass_when_minimum_bid_exceeds_valuation() -> None:
    state = _state_with_active_auction(high_bid_amount=1000)
    pack = build_ai_context_pack(state, player_id=AI_PLAYER_ID)

    guidance = pack["action_selection_guidance"]
    assert guidance["auction_guidance"]["minimum_bid"] == 1001
    assert guidance["auction_guidance"]["valuation_ceiling"] == 160

    guidance_text = " ".join(guidance["turn_guidance"])
    assert "PASS_AUCTION" in guidance_text
    assert "above the valuation ceiling" in guidance_text


def test_context_pack_redacts_profile_seed_source_from_prompt() -> None:
    state = _state()
    hidden_seed = "hidden-profile-seed-must-not-reach-prompt"
    pack = build_ai_context_pack(
        state,
        player_id=AI_PLAYER_ID,
        ai_profile={
            "id": AI_PROFILE_ID,
            "player_id": AI_PLAYER_ID,
            "persona_name": "Calculated Deal Architect",
            "persona_summary": {
                "summary": "Grace seeks enforceable deals while protecting liquidity."
            },
            "strategy_profile": {
                "risk_tolerance": 0.35,
                "liquidity_preference": 0.72,
                "debt_appetite": 0.41,
                "aggressiveness": 0.62,
                "cooperation": 0.8,
                "negotiation_creativity": 0.9,
                "trust": 0.55,
                "monopoly_focus": 0.67,
                "personality": "Collaborative but strategic.",
                "play_style": "Prioritizes color-set completion.",
                "persona_summary": "Visible strategy summary remains prompt-safe.",
                "traits": ["deal-friendly partner", "monopoly hunter"],
                "source": {
                    "game_seed": hidden_seed,
                    "seat_order": 0,
                    "player_name": "Grace",
                },
                "research_notes": {
                    "visible_hint": "Prefer exact-term deals.",
                    "game_seed": hidden_seed,
                },
                "scenario_weights": [
                    {"name": "auction", "weight": 0.4, "game_seed": hidden_seed},
                    {"name": "rent-defense", "weight": 0.6},
                ],
            },
        },
    )

    strategy_profile = pack["personality_profile"]["strategy_profile"]

    assert strategy_profile["risk_tolerance"] == 0.35
    assert strategy_profile["cooperation"] == 0.8
    assert strategy_profile["personality"] == "Collaborative but strategic."
    assert strategy_profile["play_style"] == "Prioritizes color-set completion."
    assert strategy_profile["persona_summary"] == "Visible strategy summary remains prompt-safe."
    assert strategy_profile["research_notes"]["visible_hint"] == "Prefer exact-term deals."
    assert strategy_profile["scenario_weights"] == [
        {"name": "auction", "weight": 0.4},
        {"name": "rent-defense", "weight": 0.6},
    ]

    serialized_strategy_profile = json.dumps(strategy_profile, sort_keys=True)
    serialized_prompt_context = json.dumps(pack, sort_keys=True)

    assert "source" not in strategy_profile
    assert "source" not in serialized_strategy_profile
    assert "game_seed" not in serialized_strategy_profile
    assert hidden_seed not in serialized_prompt_context


@pytest.mark.asyncio
async def test_context_pack_includes_only_negotiation_messages_visible_to_acting_ai(
    session_factory: async_sessionmaker,
) -> None:
    state = _state()
    await _insert_context_fixture(session_factory, state)
    try:
        async with session_factory() as session:
            pack = await build_ai_context_pack_from_db(
                session,
                state=state,
                game_id=GAME_ID,
                player_id=AI_PLAYER_ID,
                decision_type="negotiation_response",
            )

        messages_by_body = {
            message["body"]: message
            for message in pack["negotiation_context"]["public_messages"]
        }

        public_message = messages_by_body[
            "I can trade cash now for future consideration."
        ]
        assert public_message["sender_player_id"] == str(AI_PLAYER_ID)
        assert public_message["recipient_player_id"] is None

        sent_by_ai_message = messages_by_body[
            "Grace privately offers Ada a side payment."
        ]
        assert sent_by_ai_message["sender_player_id"] == str(AI_PLAYER_ID)
        assert sent_by_ai_message["recipient_player_id"] == str(OTHER_PLAYER_ID)

        addressed_to_ai_message = messages_by_body[
            "Ada privately asks Grace to sweeten the deal."
        ]
        assert addressed_to_ai_message["sender_player_id"] == str(OTHER_PLAYER_ID)
        assert addressed_to_ai_message["recipient_player_id"] == str(AI_PLAYER_ID)

        assert "Ada privately tells Lin not to trust Grace." not in messages_by_body
    finally:
        await _delete_game(session_factory)


@pytest.mark.asyncio
async def test_context_pack_persists_as_orchestrator_prompt_context_without_mutating_actions(
    session_factory: async_sessionmaker,
    tmp_path: Path,
) -> None:
    state = _state()
    await _insert_context_fixture(session_factory, state)
    try:
        async with session_factory() as session:
            pack = await build_ai_context_pack_from_db(
                session,
                state=state,
                game_id=GAME_ID,
                player_id=AI_PLAYER_ID,
                decision_type="action_decision",
                rule_snippets=[
                    {
                        "id": "phase-window",
                        "source": "rules",
                        "text": "ROLL_DICE is legal in START_TURN.",
                    }
                ],
            )

        runner = FakeCodexRunner(final_output=_valid_action_output(state))
        result = await request_codex_ai_decision(
            session_factory,
            CodexExecAIDecisionRequest(
                game_id=GAME_ID,
                player_id=AI_PLAYER_ID,
                ai_profile_id=AI_PROFILE_ID,
                decision_type="action_decision",
                phase=state.turn.phase.value,
                state_hash=state.state_hash(),
                prompt_context=pack,
                timeout_seconds=7,
            ),
            runner=runner,
            schema_file=tmp_path / "schema.json",
            sandbox_dir=tmp_path / "sandbox",
            work_dir=tmp_path / "work",
        )
        rows = await _fetch_ai_decision_rows(session_factory)

        assert result.status == "validated"
        assert len(rows) == 1
        stored_context = rows[0]["prompt_context"]
        assert stored_context == pack
        assert rows[0]["prompt_context_hash"] == result.prompt_context_hash
        stored_message_bodies = {
            message["body"]
            for message in stored_context["negotiation_context"]["public_messages"]
        }
        assert "I can trade cash now for future consideration." in stored_message_bodies
        assert stored_context["negotiation_context"]["public_deals"][0]["id"] == str(DEAL_ID)
        assert stored_context["contracts"]["active_contracts"][0]["id"] == str(CONTRACT_ID)
        assert stored_context["contracts"]["active_obligations"][0]["id"] == str(OBLIGATION_ID)

        memory_text = json.dumps(stored_context["memory"]["snippets"], sort_keys=True)
        assert "Own private valuation memory." in memory_text
        assert "Table-visible memory from another player." in memory_text
        assert "Other AI private memory leak." not in memory_text
        assert await _count_events(session_factory) == 0
        assert "Other AI private memory leak." not in runner.calls[0]["stdin"]
    finally:
        await _delete_game(session_factory)


@pytest.mark.asyncio
async def test_stage_8_2_memory_later_context_pack_includes_prior_memory_without_other_ai_private_memory(
    session_factory: async_sessionmaker,
) -> None:
    state = _state()
    await _insert_context_fixture(session_factory, state)
    try:
        async with session_factory() as session:
            pack = await build_ai_context_pack_from_db(
                session,
                state=state,
                game_id=GAME_ID,
                player_id=AI_PLAYER_ID,
                decision_type="action_decision",
            )

        snippets = pack["memory"]["snippets"]
        memory_text = json.dumps(snippets, sort_keys=True)

        assert "Own private valuation memory." in memory_text
        assert "Table-visible memory from another player." in memory_text
        assert "Other AI private memory leak." not in memory_text
        assert {snippet["category"] for snippet in snippets} >= {
            "strategic_belief",
            "deal_history",
        }
        own_memory = next(snippet for snippet in snippets if snippet["content"] == "Own private valuation memory.")
        assert own_memory["source_decision_id"] == str(OWN_MEMORY_DECISION_ID)
    finally:
        await _delete_game(session_factory)


async def _insert_context_fixture(
    session_factory: async_sessionmaker,
    state: GameState,
) -> None:
    async with session_factory() as session:
        async with session.begin():
            await session.execute(games.delete().where(games.c.id == GAME_ID))
            await session.execute(
                games.insert().values(
                    id=GAME_ID,
                    status="active",
                    ruleset_version=state.ruleset_version,
                    seed=state.seed,
                    current_phase=state.turn.phase.value,
                    settings={},
                    initial_state=state.model_dump(mode="json"),
                )
            )
            for seat_order, player_state in enumerate(state.players):
                await session.execute(
                    players.insert().values(
                        id=UUID(player_state.id),
                        game_id=GAME_ID,
                        seat_order=seat_order,
                        name=player_state.name,
                        controller_type=player_state.kind,
                        state=player_state.model_dump(mode="json"),
                    )
                )
            await session.execute(
                ai_profiles.insert().values(
                    id=AI_PROFILE_ID,
                    game_id=GAME_ID,
                    player_id=AI_PLAYER_ID,
                    persona_name="Test Persona",
                    strategy_profile={"risk_tolerance": 0.4, "cooperation": 0.7},
                    persona_summary={"summary": "A deterministic auction-aware AI."},
                )
            )
            await _insert_memory_rows(session)
            await _insert_negotiation_rows(session)
            await _insert_contract_rows(session)


async def _insert_memory_rows(session: AsyncSession) -> None:
    for decision_id, player_id in (
        (OWN_MEMORY_DECISION_ID, AI_PLAYER_ID),
        (OTHER_PRIVATE_MEMORY_DECISION_ID, THIRD_PLAYER_ID),
        (TABLE_MEMORY_DECISION_ID, OTHER_PLAYER_ID),
    ):
        await session.execute(
            ai_decisions.insert().values(
                id=decision_id,
                game_id=GAME_ID,
                player_id=player_id,
                ai_profile_id=AI_PROFILE_ID if player_id == AI_PLAYER_ID else None,
                decision_type="memory_update",
                status="validated",
                phase="START_TURN",
                state_hash="stage-8-2-context-memory-state",
                prompt_context_hash=f"stage-8-2-memory-{decision_id}",
                prompt_context={"stage": "8.2", "fixture": "context-pack-memory"},
                raw_output="{}",
                parsed_output={"memory_updates": []},
                validation_result={"status": "valid"},
            )
        )
    rows = [
        {
            "game_id": GAME_ID,
            "player_id": AI_PLAYER_ID,
            "ai_profile_id": AI_PROFILE_ID,
            "source_decision_id": OWN_MEMORY_DECISION_ID,
            "category": "strategic_belief",
            "visibility": "private",
            "content": "Own private valuation memory.",
            "importance": 9,
            "metadata_blob": {"source": "test"},
        },
        {
            "game_id": GAME_ID,
            "player_id": THIRD_PLAYER_ID,
            "ai_profile_id": None,
            "source_decision_id": OTHER_PRIVATE_MEMORY_DECISION_ID,
            "category": "player_trust_model",
            "visibility": "private",
            "content": "Other AI private memory leak.",
            "importance": 10,
            "metadata_blob": {"source": "test"},
        },
        {
            "game_id": GAME_ID,
            "player_id": OTHER_PLAYER_ID,
            "ai_profile_id": None,
            "source_decision_id": TABLE_MEMORY_DECISION_ID,
            "category": "deal_history",
            "visibility": "table",
            "content": "Table-visible memory from another player.",
            "importance": 6,
            "metadata_blob": {"source": "test"},
        },
    ]
    for row in rows:
        await session.execute(ai_memory_entries.insert().values(**row))


async def _insert_negotiation_rows(session: AsyncSession) -> None:
    await session.execute(
        negotiations.insert().values(
            id=NEGOTIATION_ID,
            game_id=GAME_ID,
            opened_by_player_id=AI_PLAYER_ID,
            status="active",
            phase="START_TURN",
            round_number=1,
            context={
                "participant_player_ids": [
                    str(AI_PLAYER_ID),
                    str(OTHER_PLAYER_ID),
                    str(THIRD_PLAYER_ID),
                ],
                "context": {"topic": "cash-for-favor"},
                "pending_deal_id": str(DEAL_ID),
            },
        )
    )
    await session.execute(
        negotiation_messages.insert().values(
            game_id=GAME_ID,
            negotiation_id=NEGOTIATION_ID,
            sender_player_id=AI_PLAYER_ID,
            recipient_player_id=None,
            message_type="freeform_message",
            body="I can trade cash now for future consideration.",
            payload={"message_type": "freeform_message"},
        )
    )
    await session.execute(
        negotiation_messages.insert().values(
            game_id=GAME_ID,
            negotiation_id=NEGOTIATION_ID,
            sender_player_id=AI_PLAYER_ID,
            recipient_player_id=OTHER_PLAYER_ID,
            message_type="freeform_message",
            body="Grace privately offers Ada a side payment.",
            payload={"message_type": "freeform_message"},
        )
    )
    await session.execute(
        negotiation_messages.insert().values(
            game_id=GAME_ID,
            negotiation_id=NEGOTIATION_ID,
            sender_player_id=OTHER_PLAYER_ID,
            recipient_player_id=AI_PLAYER_ID,
            message_type="freeform_message",
            body="Ada privately asks Grace to sweeten the deal.",
            payload={"message_type": "freeform_message"},
        )
    )
    await session.execute(
        negotiation_messages.insert().values(
            game_id=GAME_ID,
            negotiation_id=NEGOTIATION_ID,
            sender_player_id=OTHER_PLAYER_ID,
            recipient_player_id=THIRD_PLAYER_ID,
            message_type="freeform_message",
            body="Ada privately tells Lin not to trust Grace.",
            payload={"message_type": "freeform_message"},
        )
    )
    await session.execute(
        deals.insert().values(
            id=DEAL_ID,
            game_id=GAME_ID,
            negotiation_id=NEGOTIATION_ID,
            proposed_by_player_id=AI_PLAYER_ID,
            parent_deal_id=None,
            status="proposed",
            version=1,
            terms={
                "kind": "structured_deal",
                "deal_schema_version": 1,
                "participants": [str(AI_PLAYER_ID), str(OTHER_PLAYER_ID)],
                "terms_hash": "test-terms-hash",
                "terms": [
                    {
                        "kind": "deferred_cash_payment",
                        "from_player_id": str(AI_PLAYER_ID),
                        "to_player_id": str(OTHER_PLAYER_ID),
                        "amount": 50,
                        "due_turn": 2,
                    }
                ],
            },
        )
    )


async def _insert_contract_rows(session: AsyncSession) -> None:
    await session.execute(
        contracts.insert().values(
            id=CONTRACT_ID,
            game_id=GAME_ID,
            deal_id=DEAL_ID,
            effective_event_id=None,
            status="active",
            terms={"source_deal_id": str(DEAL_ID), "terms": [{"kind": "deferred_cash_payment"}]},
        )
    )
    await session.execute(
        obligations.insert().values(
            id=OBLIGATION_ID,
            game_id=GAME_ID,
            contract_id=CONTRACT_ID,
            owed_by_player_id=AI_PLAYER_ID,
            owed_to_player_id=OTHER_PLAYER_ID,
            settled_event_id=None,
            status="pending",
            obligation_type="cash_payment",
            schedule={"trigger": {"type": "round", "round": 2}},
            terms={"amount": 50},
        )
    )


def _valid_action_output(state: GameState) -> dict[str, Any]:
    return {
        "decision_type": "action_decision",
        "game_id": str(GAME_ID),
        "player_id": str(AI_PLAYER_ID),
        "expected_state_hash": state.state_hash(),
        "expected_event_sequence": state.event_sequence,
        "action": {"type": "ROLL_DICE", "payload": {}},
        "self_dialogue": {
            "status": "provided",
            "text": "Rolling is legal and moves the turn forward.",
        },
        "memory_updates": [],
        "confidence": 0.82,
        "rationale": "The backend legal action list includes ROLL_DICE.",
    }


def _state_with_orange_monopoly() -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(update={"cash": 3000})
    orange_property_ids = {
        "property_st_james_place",
        "property_tennessee_avenue",
        "property_new_york_avenue",
    }
    return state.model_copy(
        update={
            "players": (ai_player, *state.players[1:]),
            "property_ownership": tuple(
                ownership.model_copy(update={"owner_id": str(AI_PLAYER_ID)})
                if ownership.property_id in orange_property_ids
                else ownership
                for ownership in state.property_ownership
            ),
        }
    )


def _state_with_orange_near_monopoly() -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(update={"cash": 1500})
    other_player = state.players[1].model_copy(update={"cash": 1500})
    owner_by_property_id = {
        "property_st_james_place": str(AI_PLAYER_ID),
        "property_new_york_avenue": str(AI_PLAYER_ID),
        "property_tennessee_avenue": str(OTHER_PLAYER_ID),
    }
    return state.model_copy(
        update={
            "players": (ai_player, other_player, *state.players[2:]),
            "property_ownership": tuple(
                ownership.model_copy(update={"owner_id": owner_by_property_id[ownership.property_id]})
                if ownership.property_id in owner_by_property_id
                else ownership
                for ownership in state.property_ownership
            ),
        }
    )


def _state_with_owned_railroad(*, cash: int) -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(update={"cash": cash})
    return state.model_copy(
        update={
            "players": (ai_player, *state.players[1:]),
            "property_ownership": tuple(
                ownership.model_copy(update={"owner_id": str(AI_PLAYER_ID)})
                if ownership.property_id == "property_b_and_o_railroad"
                else ownership
                for ownership in state.property_ownership
            ),
        }
    )


def _state_with_active_debt_and_owned_railroad(*, cash: int) -> GameState:
    state = _state_with_owned_railroad(cash=cash)
    return GameState.model_validate(
        {
            **state.model_dump(mode="python"),
            "turn": {
                **state.turn.model_dump(mode="python"),
                "phase": TurnPhase.PAYMENT_RESOLUTION,
            },
            "active_payment": {
                "debtor_id": str(AI_PLAYER_ID),
                "creditor_id": str(OTHER_PLAYER_ID),
                "amount_owed": 350,
                "amount_paid": 0,
                "reason": "rent",
                "negotiation_allowed": False,
            },
        }
    )


def _state_with_mortgaged_railroad(*, cash: int) -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(update={"cash": cash})
    return state.model_copy(
        update={
            "players": (ai_player, *state.players[1:]),
            "property_ownership": tuple(
                ownership.model_copy(update={"owner_id": str(AI_PLAYER_ID), "mortgaged": True})
                if ownership.property_id == "property_b_and_o_railroad"
                else ownership
                for ownership in state.property_ownership
            ),
        }
    )


def _state_with_jail_card(*, cash: int) -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(
        update={
            "cash": cash,
            "position": 10,
            "in_jail": True,
            "jail_turns": 1,
            "get_out_of_jail_card_ids": ("card_community_get_out_of_jail",),
        }
    )
    return state.model_copy(update={"players": (ai_player, *state.players[1:])})


def _state_landed_on_unowned_reading_railroad(*, cash: int) -> GameState:
    state = _state()
    ai_player = state.players[0].model_copy(update={"cash": cash, "position": 5})
    return GameState.model_validate(
        {
            **state.model_dump(mode="python"),
            "players": (ai_player.model_dump(mode="python"), *[
                player.model_dump(mode="python") for player in state.players[1:]
            ]),
            "turn": {
                **state.turn.model_dump(mode="python"),
                "phase": TurnPhase.PURCHASE_OR_AUCTION,
            },
        }
    )


def _state_with_active_auction(*, high_bid_amount: int = 50) -> GameState:
    state = _state()
    return GameState.model_validate(
        {
            **state.model_dump(mode="python"),
            "turn": {
                **state.turn.model_dump(mode="python"),
                "phase": TurnPhase.PURCHASE_OR_AUCTION,
            },
            "active_auction": {
                "property_id": "property_virginia_avenue",
                "high_bidder_id": str(OTHER_PLAYER_ID),
                "high_bid_amount": high_bid_amount,
                "passed_player_ids": [],
            },
        }
    )


async def _fetch_ai_decision_rows(session_factory: async_sessionmaker) -> list[dict[str, Any]]:
    async with session_factory() as session:
        result = await session.execute(
            sa.select(ai_decisions)
            .where(
                ai_decisions.c.game_id == GAME_ID,
                ai_decisions.c.decision_type == "action_decision",
            )
            .order_by(ai_decisions.c.created_at.desc(), ai_decisions.c.id.desc())
        )
        return [dict(row) for row in result.mappings().all()]


async def _count_events(session_factory: async_sessionmaker) -> int:
    async with session_factory() as session:
        result = await session.execute(
            sa.select(sa.func.count()).select_from(game_events).where(game_events.c.game_id == GAME_ID)
        )
        return int(result.scalar_one())


async def _delete_game(session_factory: async_sessionmaker) -> None:
    async with session_factory() as session:
        async with session.begin():
            await session.execute(games.delete().where(games.c.id == GAME_ID))
