"""Audit-ready AI context packs for Codex decision requests.

The context pack is a public projection plus explicitly visible AI support context.
It does not serialize raw game state because raw state contains private engine internals
such as deck order and RNG counters.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping, Sequence
from typing import Any, TypeAlias
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.ai.decision_schema import AI_OUTPUT_SCHEMA
from app.db.metadata import (
    ai_memory_entries,
    ai_profiles,
    contracts,
    deals,
    negotiation_messages,
    negotiations,
    obligations,
)
from app.db.persistence import EventPersistence
from app.rules.actions import list_legal_actions
from app.rules.phases import TurnPhase
from app.rules.state import GameState
from app.rules.static_data import load_classic_monopoly_data
from app.rules.timing import ACTION_TIMING_WINDOWS


CONTEXT_PACK_SCHEMA_VERSION = "ai-context-pack-v1"
VISIBLE_MEMORY_SCOPES = frozenset({"public", "table", "audit"})
ACTIVE_NEGOTIATION_STATUSES = ("opened", "active", "countered", "accepted")
AIContextPack: TypeAlias = dict[str, Any]


def build_ai_context_pack(
    state: GameState,
    *,
    player_id: str | UUID,
    decision_type: str = "action_decision",
    ai_profile: Mapping[str, Any] | None = None,
    negotiations: Sequence[Mapping[str, Any]] = (),
    negotiation_messages: Sequence[Mapping[str, Any]] = (),
    deals: Sequence[Mapping[str, Any]] = (),
    contracts: Sequence[Mapping[str, Any]] = (),
    obligations: Sequence[Mapping[str, Any]] = (),
    memory_snippets: Sequence[Mapping[str, Any]] = (),
    rule_snippets: Sequence[Mapping[str, Any]] = (),
) -> AIContextPack:
    """Build a deterministic, JSON-safe prompt context for one AI player.

    Legal actions are always generated by the backend rules engine. Callers may supply
    already-retrieved memory and rule snippets, but memory visibility is enforced here
    as a final guard before the context reaches Codex.
    """

    actor_id = str(player_id)
    legal_actions = [action.model_dump(mode="json") for action in list_legal_actions(state, actor_id)]
    pack = {
        "context_pack_schema_version": CONTEXT_PACK_SCHEMA_VERSION,
        "decision_type": decision_type,
        "game_id": state.game_id,
        "player_id": actor_id,
        "public_game_state": _public_game_state_summary(state),
        "timing": _timing_context(state, legal_actions),
        "legal_actions": legal_actions,
        "negotiation_context": {
            "active_negotiations": [
                _public_negotiation(row) for row in _sorted_rows(negotiations)
            ],
            "public_messages": [
                _public_negotiation_message(row)
                for row in _sorted_rows(negotiation_messages)
                if _is_public_negotiation_message(row)
            ],
            "public_deals": [_public_deal(row) for row in _sorted_rows(deals)],
        },
        "contracts": {
            "active_contracts": [_public_contract(row) for row in _sorted_rows(contracts)],
            "active_obligations": [_public_obligation(row) for row in _sorted_rows(obligations)],
        },
        "memory": {
            "visibility_policy": {
                "own_private_memory_visible": True,
                "public_table_audit_memory_visible": True,
                "other_player_private_memory_visible": False,
            },
            "snippets": [
                _memory_snippet(row)
                for row in _sorted_memory_rows(memory_snippets)
                if _memory_visible_to_player(row, actor_id)
            ],
        },
        "rules": {
            "snippets": _rule_snippets(rule_snippets, legal_actions=legal_actions, state=state),
        },
        "personality_profile": _profile_summary(ai_profile),
        "required_output_schema": _json_safe(AI_OUTPUT_SCHEMA),
        "instruction_contract": _instruction_contract(),
    }
    return _json_safe(pack)


async def build_ai_context_pack_from_db(
    session: AsyncSession,
    *,
    game_id: str | UUID,
    player_id: str | UUID,
    state: GameState | None = None,
    session_factory: async_sessionmaker[AsyncSession] | None = None,
    decision_type: str = "action_decision",
    negotiation_id: str | UUID | None = None,
    rule_snippets: Sequence[Mapping[str, Any]] = (),
    max_memory_snippets: int = 12,
    max_negotiations: int = 10,
    max_negotiation_messages: int = 40,
    max_deals: int = 20,
) -> dict[str, Any]:
    """Load visible AI context rows and build a Stage 7.4 context pack."""

    game_uuid = _coerce_uuid(game_id)
    player_uuid = _coerce_uuid(player_id)
    negotiation_uuid = None if negotiation_id is None else _coerce_uuid(negotiation_id)
    if state is None:
        if session_factory is None:
            raise ValueError("session_factory is required when state is not supplied")
        state = await EventPersistence(session_factory).replay_current_state_for_update(
            session,
            game_uuid,
        )

    ai_profile = await _load_ai_profile(session, game_id=game_uuid, player_id=player_uuid)
    memory_rows = await _load_visible_memory_rows(
        session,
        game_id=game_uuid,
        player_id=player_uuid,
        limit=max_memory_snippets,
    )
    negotiation_rows = await _load_negotiation_rows(
        session,
        game_id=game_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_negotiations,
    )
    message_rows = await _load_negotiation_message_rows(
        session,
        game_id=game_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_negotiation_messages,
    )
    deal_rows = await _load_deal_rows(
        session,
        game_id=game_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_deals,
    )
    contract_rows = await _load_contract_rows(session, game_id=game_uuid)
    obligation_rows = await _load_obligation_rows(session, game_id=game_uuid)

    return build_ai_context_pack(
        state,
        player_id=player_uuid,
        decision_type=decision_type,
        ai_profile=ai_profile,
        negotiations=negotiation_rows,
        negotiation_messages=message_rows,
        deals=deal_rows,
        contracts=contract_rows,
        obligations=obligation_rows,
        memory_snippets=memory_rows,
        rule_snippets=rule_snippets,
    )


async def _load_ai_profile(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
) -> Mapping[str, Any] | None:
    result = await session.execute(
        sa.select(ai_profiles).where(
            ai_profiles.c.game_id == game_id,
            ai_profiles.c.player_id == player_id,
        )
    )
    row = result.mappings().first()
    return None if row is None else dict(row)


async def _load_visible_memory_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
    limit: int,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(ai_memory_entries)
        .where(
            ai_memory_entries.c.game_id == game_id,
            sa.or_(
                ai_memory_entries.c.player_id == player_id,
                ai_memory_entries.c.visibility.in_(tuple(sorted(VISIBLE_MEMORY_SCOPES))),
            ),
        )
        .order_by(
            ai_memory_entries.c.importance.desc(),
            ai_memory_entries.c.created_at.desc(),
            ai_memory_entries.c.id.desc(),
        )
        .limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_negotiation_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(negotiations).where(
        negotiations.c.game_id == game_id,
        negotiations.c.status.in_(ACTIVE_NEGOTIATION_STATUSES),
    )
    if negotiation_id is not None:
        statement = statement.where(negotiations.c.id == negotiation_id)
    result = await session.execute(
        statement.order_by(
            negotiations.c.updated_at.desc(),
            negotiations.c.created_at.desc(),
            negotiations.c.id.desc(),
        ).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_negotiation_message_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(negotiation_messages).where(
        negotiation_messages.c.game_id == game_id,
        negotiation_messages.c.recipient_player_id.is_(None),
    )
    if negotiation_id is not None:
        statement = statement.where(negotiation_messages.c.negotiation_id == negotiation_id)
    result = await session.execute(
        statement.order_by(
            negotiation_messages.c.created_at.desc(),
            negotiation_messages.c.id.desc(),
        ).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_deal_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(deals).where(deals.c.game_id == game_id)
    if negotiation_id is not None:
        statement = statement.where(deals.c.negotiation_id == negotiation_id)
    result = await session.execute(
        statement.order_by(deals.c.created_at.desc(), deals.c.id.desc()).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_contract_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(contracts)
        .where(contracts.c.game_id == game_id, contracts.c.status == "active")
        .order_by(contracts.c.created_at, contracts.c.id)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_obligation_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(obligations)
        .where(obligations.c.game_id == game_id, obligations.c.status == "pending")
        .order_by(obligations.c.created_at, obligations.c.id)
    )
    return [dict(row) for row in result.mappings().all()]


def _public_game_state_summary(state: GameState) -> dict[str, Any]:
    data = load_classic_monopoly_data()
    spaces_by_position = {space.position: space for space in data.board}
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    owned_property_ids_by_player = _owned_property_ids_by_player(state)

    return {
        "game_id": state.game_id,
        "ruleset_version": state.ruleset_version,
        "state_hash": state.state_hash(),
        "event_sequence": state.event_sequence,
        "turn": {
            "turn_number": state.turn.turn_number,
            "current_player_index": state.turn.current_player_index,
            "current_player_id": state.turn.current_player_id,
            "phase": state.turn.phase.value,
            "consecutive_doubles": state.turn.consecutive_doubles,
        },
        "players": [
            {
                "id": player.id,
                "name": player.name,
                "kind": player.kind,
                "cash": player.cash,
                "position": player.position,
                "space": _space_summary(spaces_by_position[player.position]),
                "in_jail": player.in_jail,
                "jail_turns": player.jail_turns,
                "get_out_of_jail_card_count": len(player.get_out_of_jail_card_ids),
                "is_bankrupt": player.is_bankrupt,
                "owned_property_ids": owned_property_ids_by_player.get(player.id, []),
            }
            for player in state.players
        ],
        "property_ownership": [
            {
                "property_id": ownership.property_id,
                "name": properties_by_id[ownership.property_id].name,
                "group": properties_by_id[ownership.property_id].group,
                "kind": properties_by_id[ownership.property_id].kind,
                "board_position": properties_by_id[ownership.property_id].board_position,
                "price": properties_by_id[ownership.property_id].price,
                "owner_id": ownership.owner_id,
                "mortgaged": ownership.mortgaged,
                "houses": ownership.houses,
                "hotel": ownership.hotel,
            }
            for ownership in state.property_ownership
        ],
        "bank_inventory": {
            "houses": state.bank_inventory.houses,
            "hotels": state.bank_inventory.hotels,
        },
        "active_payment": None
        if state.active_payment is None
        else state.active_payment.model_dump(mode="json"),
        "active_auction": None
        if state.active_auction is None
        else state.active_auction.model_dump(mode="json"),
        "active_bankruptcy": None
        if state.active_bankruptcy is None
        else state.active_bankruptcy.model_dump(mode="json"),
        "active_atomic_resolution": None
        if state.active_atomic_resolution is None
        else state.active_atomic_resolution.model_dump(mode="json"),
    }


def _timing_context(
    state: GameState,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    legal_action_types = sorted(
        {str(action["type"]) for action in legal_actions if isinstance(action.get("type"), str)}
    )
    return {
        "active_phase": state.turn.phase.value,
        "current_player_id": state.turn.current_player_id,
        "turn_number": state.turn.turn_number,
        "timing_window": {
            "phase": state.turn.phase.value,
            "backend_legal_action_types": legal_action_types,
        },
        "backend_defined_action_windows": {
            action_type: _phase_values(ACTION_TIMING_WINDOWS[action_type])
            for action_type in legal_action_types
            if action_type in ACTION_TIMING_WINDOWS
        },
    }


def _owned_property_ids_by_player(state: GameState) -> dict[str, list[str]]:
    owned: dict[str, list[str]] = {player.id: [] for player in state.players}
    for ownership in state.property_ownership:
        if ownership.owner_id is not None:
            owned.setdefault(ownership.owner_id, []).append(ownership.property_id)
    return {player_id: sorted(property_ids) for player_id, property_ids in owned.items()}


def _space_summary(space: Any) -> dict[str, Any]:
    return {
        "id": space.id,
        "name": space.name,
        "position": space.position,
        "type": space.type,
        "property_id": space.property_id,
    }


def _public_negotiation(row: Mapping[str, Any]) -> dict[str, Any]:
    context = _mapping(row.get("context"))
    return {
        "id": _string_or_none(row.get("id")),
        "opened_by_player_id": _string_or_none(row.get("opened_by_player_id")),
        "status": _string_or_none(row.get("status")),
        "phase": _string_or_none(row.get("phase")),
        "round_number": row.get("round_number"),
        "participant_player_ids": _string_list(context.get("participant_player_ids")),
        "pending_deal_id": _string_or_none(context.get("pending_deal_id")),
        "current_deal_id": _string_or_none(context.get("current_deal_id")),
        "current_terms_hash": _string_or_none(context.get("current_terms_hash")),
        "context": _mapping(context.get("context")),
        "cutoff_policy": _mapping(context.get("cutoff_policy")),
        "cutoff_reason": _string_or_none(context.get("cutoff_reason")),
        "expired_by_cutoff": bool(context.get("expired_by_cutoff", False)),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "closed_at": _string_or_none(row.get("closed_at")),
    }


def _public_negotiation_message(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "negotiation_id": _string_or_none(row.get("negotiation_id")),
        "sender_player_id": _string_or_none(row.get("sender_player_id")),
        "recipient_player_id": _string_or_none(row.get("recipient_player_id")),
        "message_type": _string_or_none(row.get("message_type")),
        "body": row.get("body"),
        "payload": _mapping(row.get("payload")),
        "created_at": _string_or_none(row.get("created_at")),
    }


def _public_deal(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "negotiation_id": _string_or_none(row.get("negotiation_id")),
        "proposed_by_player_id": _string_or_none(row.get("proposed_by_player_id")),
        "parent_deal_id": _string_or_none(row.get("parent_deal_id")),
        "status": _string_or_none(row.get("status")),
        "version": row.get("version"),
        "terms": _mapping(row.get("terms")),
        "validation_errors": _json_safe(row.get("validation_errors")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "accepted_at": _string_or_none(row.get("accepted_at")),
    }


def _public_contract(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "deal_id": _string_or_none(row.get("deal_id")),
        "effective_event_id": _string_or_none(row.get("effective_event_id")),
        "status": _string_or_none(row.get("status")),
        "terms": _mapping(row.get("terms")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "executed_at": _string_or_none(row.get("executed_at")),
        "closed_at": _string_or_none(row.get("closed_at")),
    }


def _public_obligation(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "contract_id": _string_or_none(row.get("contract_id")),
        "owed_by_player_id": _string_or_none(row.get("owed_by_player_id")),
        "owed_to_player_id": _string_or_none(row.get("owed_to_player_id")),
        "settled_event_id": _string_or_none(row.get("settled_event_id")),
        "status": _string_or_none(row.get("status")),
        "obligation_type": _string_or_none(row.get("obligation_type")),
        "schedule": _mapping(row.get("schedule")),
        "terms": _mapping(row.get("terms")),
        "due_at": _string_or_none(row.get("due_at")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
    }


def _memory_visible_to_player(row: Mapping[str, Any], actor_id: str) -> bool:
    visibility = str(row.get("visibility", "private"))
    row_player_id = _string_or_none(row.get("player_id"))
    return row_player_id == actor_id or visibility in VISIBLE_MEMORY_SCOPES


def _memory_snippet(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "player_id": _string_or_none(row.get("player_id")),
        "ai_profile_id": _string_or_none(row.get("ai_profile_id")),
        "visibility": _string_or_none(row.get("visibility")) or "private",
        "category": _string_or_none(row.get("category")),
        "content": _string_or_none(row.get("content")),
        "importance": row.get("importance"),
        "metadata": _mapping(row.get("metadata_blob", row.get("metadata"))),
        "source_decision_id": _string_or_none(row.get("source_decision_id")),
        "source_event_id": _string_or_none(row.get("source_event_id")),
        "source_negotiation_message_id": _string_or_none(
            row.get("source_negotiation_message_id")
        ),
        "created_at": _string_or_none(row.get("created_at")),
    }


def _rule_snippets(
    rule_snippets: Sequence[Mapping[str, Any]],
    *,
    legal_actions: Sequence[Mapping[str, Any]],
    state: GameState,
) -> list[dict[str, Any]]:
    if rule_snippets:
        return [_json_safe(dict(snippet)) for snippet in rule_snippets]

    legal_action_types = sorted(
        {str(action["type"]) for action in legal_actions if isinstance(action.get("type"), str)}
    )
    return [
        {
            "id": "backend-rules-authority",
            "source": "backend",
            "text": "The FastAPI backend rules engine is authoritative for legal actions.",
        },
        {
            "id": f"phase-{state.turn.phase.value.lower()}-legal-actions",
            "source": "backend:list_legal_actions",
            "text": (
                f"During {state.turn.phase.value}, this player may choose only from "
                f"these backend-generated legal action types: {', '.join(legal_action_types)}."
            ),
        },
    ]


def _profile_summary(ai_profile: Mapping[str, Any] | None) -> dict[str, Any]:
    if ai_profile is None:
        return {
            "profile_found": False,
            "id": None,
            "player_id": None,
            "persona_name": None,
            "persona_summary": None,
            "strategy_profile": {},
        }

    persona_summary = ai_profile.get("persona_summary")
    summary_text = None
    if isinstance(persona_summary, Mapping):
        summary_text = _string_or_none(persona_summary.get("summary"))
    return {
        "profile_found": True,
        "id": _string_or_none(ai_profile.get("id")),
        "player_id": _string_or_none(ai_profile.get("player_id")),
        "persona_name": _string_or_none(ai_profile.get("persona_name")),
        "persona_summary": summary_text or _string_or_none(persona_summary),
        "strategy_profile": _mapping(ai_profile.get("strategy_profile")),
    }


def _instruction_contract() -> dict[str, Any]:
    return {
        "backend_is_rules_authority": True,
        "choose_only_from_legal_actions": True,
        "do_not_infer_hidden_context": True,
        "do_not_mutate_state_directly": True,
        "return_exactly_one_schema_valid_json_object": True,
        "no_fallback_actions": True,
        "no_default_random_coerced_or_substitute_move": True,
        "invalid_output_will_be_rejected_without_game_mutation": True,
        "required_output_schema_name": "AIDecisionOutput",
        "instructions": [
            "Choose action_decision.action only from legal_actions when making a game action.",
            "Use expected_state_hash and expected_event_sequence from a chosen legal action.",
            "Negotiation text may use only public negotiation context and visible memory snippets.",
            "Do not rely on hidden deck order, RNG state, or another player's private memory.",
            "Return self_dialogue and memory_updates according to the required output schema.",
        ],
    }


def _is_public_negotiation_message(row: Mapping[str, Any]) -> bool:
    return row.get("recipient_player_id") is None


def _sorted_rows(rows: Sequence[Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    return sorted(rows, key=lambda row: (_string_or_none(row.get("created_at")) or "", _row_id(row)))


def _sorted_memory_rows(rows: Sequence[Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    return sorted(
        rows,
        key=lambda row: (
            -_int_or_zero(row.get("importance")),
            _string_or_none(row.get("created_at")) or "",
            _row_id(row),
        ),
    )


def _phase_values(phases: Iterable[TurnPhase]) -> list[str]:
    phase_order = {phase: index for index, phase in enumerate(TurnPhase)}
    return [
        phase.value
        for phase in sorted(phases, key=lambda phase: phase_order.get(phase, len(phase_order)))
    ]


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, Sequence) or isinstance(value, str | bytes | bytearray):
        return []
    return [str(item) for item in value]


def _mapping(value: Any) -> dict[str, Any]:
    return _json_safe(value) if isinstance(value, Mapping) else {}


def _string_or_none(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def _int_or_zero(value: Any) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, int):
        return value
    return 0


def _row_id(row: Mapping[str, Any]) -> str:
    return _string_or_none(row.get("id")) or ""


def _coerce_uuid(value: str | UUID) -> UUID:
    if isinstance(value, UUID):
        return value
    return UUID(str(value))


def _json_safe(value: Any) -> Any:
    return json.loads(json.dumps(value, sort_keys=True, default=str, ensure_ascii=True))


__all__ = [
    "AIContextPack",
    "CONTEXT_PACK_SCHEMA_VERSION",
    "VISIBLE_MEMORY_SCOPES",
    "build_ai_context_pack",
    "build_ai_context_pack_from_db",
]
