"""Audit-ready AI context packs for Codex decision requests.

The context pack is a public projection plus explicitly visible AI support context.
It does not serialize raw game state because raw state contains private engine internals
such as deck order and RNG counters.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping, Sequence
from typing import Any, TypeAlias
from uuid import UUID, uuid4

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.ai.memory import (
    MEMORY_COMPACTION_REASON_ON_DEMAND,
    MEMORY_COMPACTION_THRESHOLD,
    compact_memory_for_player,
    memory_row_is_usable_for_context,
    select_memory_rows_for_context,
)
from app.db.metadata import (
    ai_decisions,
    ai_memory_entries,
    ai_profiles,
    contracts,
    deals,
    negotiation_messages,
    negotiations,
    obligations,
)
from app.db.persistence import EventPersistence
from app.rules.actions import list_legal_actions
from app.rules.phases import TurnPhase
from app.rules.state import GameState
from app.rules.static_data import load_classic_monopoly_data
from app.rules.timing import ACTION_TIMING_WINDOWS


CONTEXT_PACK_SCHEMA_VERSION = "ai-context-pack-v1"
RETRIEVAL_AUDIT_CONTEXT_ID_KEY = "retrieval_audit_context_id"
VISIBLE_MEMORY_SCOPES = frozenset({"public", "table", "audit"})
ACTIVE_NEGOTIATION_STATUSES = ("opened", "active", "countered", "accepted")
_FIELD_JOINER = "".join
AIContextPack: TypeAlias = dict[str, Any]
MORTGAGE_HEALTHY_CASH_FLOOR = 200
PURCHASE_HEALTHY_CASH_FLOOR = 300


def build_ai_context_pack(
    state: GameState,
    *,
    player_id: str | UUID,
    decision_type: str = "action_decision",
    caller_request_context: Mapping[str, Any] | None = None,
    ai_profile: Mapping[str, Any] | None = None,
    negotiations: Sequence[Mapping[str, Any]] = (),
    negotiation_messages: Sequence[Mapping[str, Any]] = (),
    deals: Sequence[Mapping[str, Any]] = (),
    contracts: Sequence[Mapping[str, Any]] = (),
    obligations: Sequence[Mapping[str, Any]] = (),
    memory_snippets: Sequence[Mapping[str, Any]] = (),
    rule_snippets: Sequence[Mapping[str, Any]] = (),
) -> AIContextPack:
    """Build a deterministic, JSON-safe prompt context for one AI player.

    Legal actions are always generated by the backend rules engine. Callers may supply
    already-retrieved memory and rule snippets, but memory visibility is enforced here
    as a final guard before the context reaches Codex.
    """

    actor_id = str(player_id)
    legal_actions = [action.model_dump(mode="json") for action in list_legal_actions(state, actor_id)]
    pack = {
        "context_pack_schema_version": CONTEXT_PACK_SCHEMA_VERSION,
        "decision_type": decision_type,
        "game_id": state.game_id,
        "player_id": actor_id,
        "caller_request_context": _json_safe(caller_request_context or {}),
        "public_game_state": public_game_state_summary(state),
        "timing": _timing_context(state, legal_actions),
        "legal_actions": legal_actions,
        "action_selection_guidance": _action_selection_guidance(state, actor_id, legal_actions),
        "negotiation_strategy_guidance": _negotiation_strategy_guidance(
            state,
            actor_id,
            negotiations,
        ),
        "negotiation_context": {
            "active_negotiations": [
                _public_negotiation(row) for row in _sorted_rows(negotiations)
            ],
            "public_messages": [
                _public_negotiation_message(row)
                for row in _sorted_rows(negotiation_messages)
                if _is_visible_negotiation_message(row, actor_id)
            ],
            "public_deals": [_public_deal(row) for row in _sorted_rows(deals)],
        },
        "contracts": {
            "active_contracts": [_public_contract(row) for row in _sorted_rows(contracts)],
            "active_obligations": [_public_obligation(row) for row in _sorted_rows(obligations)],
        },
        "memory": {
            "visibility_policy": {
                "own_private_memory_visible": True,
                "public_table_audit_memory_visible": True,
                "other_player_private_memory_visible": False,
            },
            "snippets": [
                _memory_snippet(row)
                for row in _sorted_memory_rows(memory_snippets)
                if _memory_visible_to_player(row, actor_id)
            ],
        },
        "rules": {
            "snippets": _rule_snippets(rule_snippets, legal_actions=legal_actions, state=state),
        },
        "personality_profile": _profile_summary(ai_profile),
        "instruction_contract": _instruction_contract(),
    }
    return _json_safe(pack)


async def build_ai_context_pack_from_db(
    session: AsyncSession,
    *,
    game_id: str | UUID,
    player_id: str | UUID,
    state: GameState | None = None,
    session_factory: async_sessionmaker[AsyncSession] | None = None,
    decision_type: str = "action_decision",
    negotiation_id: str | UUID | None = None,
    caller_request_context: Mapping[str, Any] | None = None,
    rule_snippets: Sequence[Mapping[str, Any]] = (),
    max_memory_snippets: int = 12,
    retrieval_query_text: str | None = None,
    max_retrieval_snippets: int = 6,
    audit_retrieval: bool = True,
    memory_compaction_threshold: int = MEMORY_COMPACTION_THRESHOLD,
    max_negotiations: int = 10,
    max_negotiation_messages: int = 40,
    max_deals: int = 20,
) -> dict[str, Any]:
    """Load visible AI context rows and build a Stage 7.4 context pack."""

    if not session.in_transaction():
        async with session.begin():
            return await _build_ai_context_pack_from_db_in_transaction(
                session,
                game_id=game_id,
                player_id=player_id,
                state=state,
                session_factory=session_factory,
                decision_type=decision_type,
                negotiation_id=negotiation_id,
                caller_request_context=caller_request_context,
                rule_snippets=rule_snippets,
                max_memory_snippets=max_memory_snippets,
                retrieval_query_text=retrieval_query_text,
                max_retrieval_snippets=max_retrieval_snippets,
                audit_retrieval=audit_retrieval,
                memory_compaction_threshold=memory_compaction_threshold,
                max_negotiations=max_negotiations,
                max_negotiation_messages=max_negotiation_messages,
                max_deals=max_deals,
            )

    return await _build_ai_context_pack_from_db_in_transaction(
        session,
        game_id=game_id,
        player_id=player_id,
        state=state,
        session_factory=session_factory,
        decision_type=decision_type,
        negotiation_id=negotiation_id,
        caller_request_context=caller_request_context,
        rule_snippets=rule_snippets,
        max_memory_snippets=max_memory_snippets,
        retrieval_query_text=retrieval_query_text,
        max_retrieval_snippets=max_retrieval_snippets,
        audit_retrieval=audit_retrieval,
        memory_compaction_threshold=memory_compaction_threshold,
        max_negotiations=max_negotiations,
        max_negotiation_messages=max_negotiation_messages,
        max_deals=max_deals,
    )


async def _build_ai_context_pack_from_db_in_transaction(
    session: AsyncSession,
    *,
    game_id: str | UUID,
    player_id: str | UUID,
    state: GameState | None,
    session_factory: async_sessionmaker[AsyncSession] | None,
    decision_type: str,
    negotiation_id: str | UUID | None,
    caller_request_context: Mapping[str, Any] | None,
    rule_snippets: Sequence[Mapping[str, Any]],
    max_memory_snippets: int,
    retrieval_query_text: str | None,
    max_retrieval_snippets: int,
    audit_retrieval: bool,
    memory_compaction_threshold: int,
    max_negotiations: int,
    max_negotiation_messages: int,
    max_deals: int,
) -> dict[str, Any]:
    """Build the DB-backed context pack inside an existing or owned transaction."""

    game_uuid = _coerce_uuid(game_id)
    player_uuid = _coerce_uuid(player_id)
    negotiation_uuid = None if negotiation_id is None else _coerce_uuid(negotiation_id)
    if state is None:
        if session_factory is None:
            raise ValueError("session_factory is required when state is not supplied")
        state = await EventPersistence(session_factory).replay_current_state_for_update(
            session,
            game_uuid,
        )

    ai_profile = await _load_ai_profile(session, game_id=game_uuid, player_id=player_uuid)
    await compact_memory_for_player(
        session,
        game_id=game_uuid,
        player_id=player_uuid,
        reason=MEMORY_COMPACTION_REASON_ON_DEMAND,
        compaction_threshold=memory_compaction_threshold,
    )
    memory_rows = await _load_visible_memory_rows(
        session,
        game_id=game_uuid,
        player_id=player_uuid,
        limit=max_memory_snippets,
    )
    negotiation_rows = await _load_negotiation_rows(
        session,
        game_id=game_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_negotiations,
    )
    message_rows = await _load_negotiation_message_rows(
        session,
        game_id=game_uuid,
        player_id=player_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_negotiation_messages,
    )
    deal_rows = await _load_deal_rows(
        session,
        game_id=game_uuid,
        negotiation_id=negotiation_uuid,
        limit=max_deals,
    )
    contract_rows = await _load_contract_rows(session, game_id=game_uuid)
    obligation_rows = await _load_obligation_rows(session, game_id=game_uuid)
    (
        retrieval_rule_snippets,
        retrieval_memory_rows,
        retrieval_audit_context_id,
    ) = await _load_retrieved_context_rows(
        session,
        game_id=game_uuid,
        player_id=player_uuid,
        state=state,
        decision_type=decision_type,
        caller_request_context=caller_request_context,
        retrieval_query_text=retrieval_query_text,
        phase=state.turn.phase.value,
        limit=max_retrieval_snippets,
        audit=audit_retrieval,
    )

    pack = build_ai_context_pack(
        state,
        player_id=player_uuid,
        decision_type=decision_type,
        caller_request_context=caller_request_context,
        ai_profile=ai_profile,
        negotiations=negotiation_rows,
        negotiation_messages=message_rows,
        deals=deal_rows,
        contracts=contract_rows,
        obligations=obligation_rows,
        memory_snippets=_merge_memory_rows(memory_rows, retrieval_memory_rows),
        rule_snippets=[*rule_snippets, *retrieval_rule_snippets],
    )
    if retrieval_audit_context_id is not None:
        pack[RETRIEVAL_AUDIT_CONTEXT_ID_KEY] = retrieval_audit_context_id
    return _json_safe(pack)


async def _load_retrieved_context_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
    state: GameState,
    decision_type: str,
    caller_request_context: Mapping[str, Any] | None,
    retrieval_query_text: str | None,
    phase: str,
    limit: int,
    audit: bool,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], str | None]:
    if limit < 1:
        return [], [], None

    query_text = _context_retrieval_query_text(
        retrieval_query_text=retrieval_query_text,
        caller_request_context=caller_request_context,
        state=state,
        player_id=player_id,
        decision_type=decision_type,
    )
    if not query_text:
        return [], [], None

    retrieval_audit_context_id = await _next_retrieval_audit_context_id(
        session,
        game_id=game_id,
        player_id=player_id,
        decision_type=decision_type,
        phase=phase,
        query_text=query_text,
    )

    from app.rag.retrieval import refresh_rag_index_entries, search_retrieval

    await refresh_rag_index_entries(session, game_id=game_id)
    rule_results = await search_retrieval(
        session,
        query_text=query_text,
        game_id=game_id,
        player_id=player_id,
        phase=phase,
        source_types=("rules", "house_rules", "contract_examples"),
        limit=limit,
        query_context={
            "source": "build_ai_context_pack_from_db",
            "decision_type": decision_type,
            "phase": phase,
            "retrieval_section": "rules",
            RETRIEVAL_AUDIT_CONTEXT_ID_KEY: retrieval_audit_context_id,
        },
        audit=audit,
    )
    memory_results = await search_retrieval(
        session,
        query_text=query_text,
        game_id=game_id,
        player_id=player_id,
        phase=phase,
        source_types=("ai_memory",),
        limit=min(limit, 4),
        query_context={
            "source": "build_ai_context_pack_from_db",
            "decision_type": decision_type,
            "phase": phase,
            "retrieval_section": "memory",
            RETRIEVAL_AUDIT_CONTEXT_ID_KEY: retrieval_audit_context_id,
        },
        audit=audit,
    )

    rule_snippets = [
        result.to_rule_snippet()
        for result in rule_results
    ]
    memory_rows = [
        result.to_memory_row()
        for result in memory_results
    ]
    return rule_snippets, memory_rows, retrieval_audit_context_id


async def _next_retrieval_audit_context_id(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
    decision_type: str,
    phase: str,
    query_text: str,
) -> str:
    return str(uuid4())


def _context_retrieval_query_text(
    *,
    retrieval_query_text: str | None,
    caller_request_context: Mapping[str, Any] | None,
    state: GameState,
    player_id: UUID,
    decision_type: str,
) -> str:
    explicit = _nonempty_string(retrieval_query_text)
    if explicit is not None:
        return explicit

    context = _mapping(caller_request_context)
    for key in ("retrieval_query", "retrieval_query_text", "query_text", "focus"):
        value = _nonempty_string(context.get(key))
        if value is not None:
            return value

    if decision_type == "action_decision":
        return ""

    legal_action_types = sorted(
        {
            str(action.type)
            for action in list_legal_actions(state, str(player_id))
        }
    )
    current_player = next(
        (player for player in state.players if player.id == str(player_id)),
        None,
    )
    parts = [
        decision_type,
        state.turn.phase.value,
        *(str(action_type) for action_type in legal_action_types),
    ]
    if current_player is not None:
        parts.extend([current_player.name, f"cash {current_player.cash}"])
    return " ".join(part for part in parts if part)


def _merge_memory_rows(
    base_rows: Sequence[Mapping[str, Any]],
    retrieval_rows: Sequence[Mapping[str, Any]],
) -> list[Mapping[str, Any]]:
    rows_by_id: dict[str, dict[str, Any]] = {}
    ordered_ids: list[str] = []
    anonymous_rows: list[Mapping[str, Any]] = []
    for row in [*base_rows, *retrieval_rows]:
        row_id = _string_or_none(row.get("id"))
        if row_id is None:
            anonymous_rows.append(row)
            continue
        if row_id not in rows_by_id:
            ordered_ids.append(row_id)
            rows_by_id[row_id] = dict(row)
            continue
        merged = dict(rows_by_id[row_id])
        merged.update({key: value for key, value in row.items() if value is not None})
        rows_by_id[row_id] = merged
    return [rows_by_id[row_id] for row_id in ordered_ids] + list(anonymous_rows)


def _nonempty_string(value: Any) -> str | None:
    if value is None:
        return None
    text = " ".join(str(value).split())
    return text if text else None


async def _load_ai_profile(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
) -> Mapping[str, Any] | None:
    result = await session.execute(
        sa.select(ai_profiles).where(
            ai_profiles.c.game_id == game_id,
            ai_profiles.c.player_id == player_id,
        )
    )
    row = result.mappings().first()
    return None if row is None else dict(row)


async def _load_visible_memory_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
    limit: int,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(ai_memory_entries, ai_decisions.c.status.label("source_decision_status"))
        .select_from(
            ai_memory_entries.outerjoin(
                ai_decisions,
                ai_memory_entries.c.source_decision_id == ai_decisions.c.id,
            )
        )
        .where(
            ai_memory_entries.c.game_id == game_id,
            sa.or_(
                ai_memory_entries.c.player_id == player_id,
                ai_memory_entries.c.visibility.in_(tuple(sorted(VISIBLE_MEMORY_SCOPES))),
            ),
        )
        .order_by(ai_memory_entries.c.created_at, ai_memory_entries.c.id)
    )
    rows = [dict(row) for row in result.mappings().all()]
    return select_memory_rows_for_context(
        [row for row in rows if memory_row_is_usable_for_context(row)],
        limit=limit,
    )


async def _load_negotiation_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(negotiations).where(
        negotiations.c.game_id == game_id,
        negotiations.c.status.in_(ACTIVE_NEGOTIATION_STATUSES),
    )
    if negotiation_id is not None:
        statement = statement.where(negotiations.c.id == negotiation_id)
    result = await session.execute(
        statement.order_by(
            negotiations.c.updated_at.desc(),
            negotiations.c.created_at.desc(),
            negotiations.c.id.desc(),
        ).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_negotiation_message_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    player_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(negotiation_messages).where(
        negotiation_messages.c.game_id == game_id,
        sa.or_(
            negotiation_messages.c.recipient_player_id.is_(None),
            negotiation_messages.c.sender_player_id == player_id,
            negotiation_messages.c.recipient_player_id == player_id,
        ),
    )
    if negotiation_id is not None:
        statement = statement.where(negotiation_messages.c.negotiation_id == negotiation_id)
    result = await session.execute(
        statement.order_by(
            negotiation_messages.c.created_at.desc(),
            negotiation_messages.c.id.desc(),
        ).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_deal_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
    negotiation_id: UUID | None,
    limit: int,
) -> list[dict[str, Any]]:
    statement = sa.select(deals).where(deals.c.game_id == game_id)
    if negotiation_id is not None:
        statement = statement.where(deals.c.negotiation_id == negotiation_id)
    result = await session.execute(
        statement.order_by(deals.c.created_at.desc(), deals.c.id.desc()).limit(limit)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_contract_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(contracts)
        .where(contracts.c.game_id == game_id, contracts.c.status == "active")
        .order_by(contracts.c.created_at, contracts.c.id)
    )
    return [dict(row) for row in result.mappings().all()]


async def _load_obligation_rows(
    session: AsyncSession,
    *,
    game_id: UUID,
) -> list[dict[str, Any]]:
    result = await session.execute(
        sa.select(obligations)
        .where(obligations.c.game_id == game_id, obligations.c.status == "pending")
        .order_by(obligations.c.created_at, obligations.c.id)
    )
    return [dict(row) for row in result.mappings().all()]


def public_game_state_summary(state: GameState) -> dict[str, Any]:
    data = load_classic_monopoly_data()
    spaces_by_position = {space.position: space for space in data.board}
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    owned_property_ids_by_player = _owned_property_ids_by_player(state)

    return {
        "game_id": state.game_id,
        "ruleset_version": state.ruleset_version,
        "state_hash": state.state_hash(),
        "event_sequence": state.event_sequence,
        "turn": {
            "turn_number": state.turn.turn_number,
            "current_player_index": state.turn.current_player_index,
            "current_player_id": state.turn.current_player_id,
            "phase": state.turn.phase.value,
            "consecutive_doubles": state.turn.consecutive_doubles,
        },
        "players": [
            {
                "id": player.id,
                "name": player.name,
                "kind": player.kind,
                "cash": player.cash,
                "position": player.position,
                "space": _space_summary(spaces_by_position[player.position]),
                "in_jail": player.in_jail,
                "jail_turns": player.jail_turns,
                "get_out_of_jail_card_count": len(player.get_out_of_jail_card_ids),
                "is_bankrupt": player.is_bankrupt,
                "owned_property_ids": owned_property_ids_by_player.get(player.id, []),
            }
            for player in state.players
        ],
        "property_ownership": [
            {
                "property_id": ownership.property_id,
                "name": properties_by_id[ownership.property_id].name,
                "group": properties_by_id[ownership.property_id].group,
                "kind": properties_by_id[ownership.property_id].kind,
                "board_position": properties_by_id[ownership.property_id].board_position,
                "price": properties_by_id[ownership.property_id].price,
                "owner_id": ownership.owner_id,
                "mortgaged": ownership.mortgaged,
                "houses": ownership.houses,
                "hotel": ownership.hotel,
            }
            for ownership in state.property_ownership
        ],
        "bank_inventory": {
            "houses": state.bank_inventory.houses,
            "hotels": state.bank_inventory.hotels,
        },
        "active_payment": None
        if state.active_payment is None
        else state.active_payment.model_dump(mode="json"),
        "active_auction": None
        if state.active_auction is None
        else state.active_auction.model_dump(mode="json"),
        "active_bankruptcy": None
        if state.active_bankruptcy is None
        else state.active_bankruptcy.model_dump(mode="json"),
        "active_atomic_resolution": None
        if state.active_atomic_resolution is None
        else state.active_atomic_resolution.model_dump(mode="json"),
    }


def _timing_context(
    state: GameState,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    legal_action_types = sorted(
        {str(action["type"]) for action in legal_actions if isinstance(action.get("type"), str)}
    )
    return {
        "active_phase": state.turn.phase.value,
        "current_player_id": state.turn.current_player_id,
        "turn_number": state.turn.turn_number,
        "timing_window": {
            "phase": state.turn.phase.value,
            "backend_legal_action_types": legal_action_types,
        },
        "backend_defined_action_windows": {
            action_type: _phase_values(ACTION_TIMING_WINDOWS[action_type])
            for action_type in legal_action_types
            if action_type in ACTION_TIMING_WINDOWS
        },
    }


def _action_selection_guidance(
    state: GameState,
    actor_id: str,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    legal_action_types = [
        str(action["type"]) for action in legal_actions if isinstance(action.get("type"), str)
    ]
    development_opportunities = _development_opportunities(state, actor_id, legal_actions)
    recommended_action_types: list[str] = []
    recommended_before_roll: list[str] = []
    lower_priority_action_types: list[str] = []
    turn_guidance: list[str] = []
    purchase_guidance = _purchase_guidance(state, actor_id, legal_actions)
    auction_guidance = _auction_guidance(state, actor_id, legal_actions)
    mortgage_guidance = _mortgage_guidance(state, actor_id, legal_actions)

    if purchase_guidance is not None:
        recommendation = _string_or_none(purchase_guidance.get("recommendation"))
        if recommendation == "buy_property_at_list_price":
            recommended_action_types.append("BUY_PROPERTY")
            if "START_AUCTION" in legal_action_types:
                lower_priority_action_types.append("START_AUCTION")
            turn_guidance.append(
                "Prefer BUY_PROPERTY for this landed unowned property while cash_after_price "
                "remains healthy; START_AUCTION lets competitors win the property and should "
                "need a concrete liquidity or valuation reason."
            )
        elif recommendation == "consider_auction_for_liquidity":
            turn_guidance.append(
                "START_AUCTION may be reasonable because BUY_PROPERTY cash_after_price would "
                "fall below the healthy liquidity floor; if buying anyway, explain the "
                "monopoly, railroad, utility, or blocking value."
            )

    if development_opportunities:
        recommended_before_roll.append("BUY_HOUSE")
        if "ROLL_DICE" in legal_action_types:
            lower_priority_action_types.append("ROLL_DICE")
        turn_guidance.append(
            "BUY_HOUSE is legal on a complete color group; prefer even monopoly "
            "development before ROLL_DICE when cash_after_cost remains healthy."
        )

    if auction_guidance is not None:
        minimum_bid = _int_or_zero(auction_guidance.get("minimum_bid"))
        valuation_ceiling = _int_or_zero(auction_guidance.get("valuation_ceiling"))
        turn_guidance.append(
            "For BID_AUCTION, the payload amount is the minimum legal floor, "
            "not a recommendation. If bidding, choose a deliberate value based "
            "on property price, current high bid, and cash while staying near "
            "the valuation ceiling, or PASS_AUCTION; avoid one-dollar increment loops."
        )
        if valuation_ceiling > 0 and minimum_bid > valuation_ceiling:
            turn_guidance.append(
                "Choose PASS_AUCTION when the minimum BID_AUCTION amount is "
                "above the valuation ceiling unless a concrete monopoly-completion "
                "reason justifies the overpay."
            )

    if mortgage_guidance is not None:
        recommendation = _string_or_none(mortgage_guidance.get("recommendation"))
        if recommendation == "avoid_unless_debt_or_liquidity_pressure":
            if "MORTGAGE_PROPERTY" not in lower_priority_action_types:
                lower_priority_action_types.append("MORTGAGE_PROPERTY")
            turn_guidance.append(
                "Avoid MORTGAGE_PROPERTY while cash is healthy and no active debt exists; "
                "mortgaging disables rent and creates future unmortgage interest. Use it "
                "only for active debt, bankruptcy prevention, or urgent liquidity."
            )
        elif recommendation == "liquidate_only_enough_for_active_debt":
            turn_guidance.append(
                "For MORTGAGE_PROPERTY during active debt, mortgage only enough property "
                "to cover the outstanding amount after using available cash and cheaper "
                "liquidation actions."
            )

    return {
        "recommended_action_types": recommended_action_types,
        "recommended_action_types_before_roll": recommended_before_roll,
        "lower_priority_action_types": lower_priority_action_types,
        "purchase_guidance": purchase_guidance,
        "development_opportunities": development_opportunities,
        "auction_guidance": auction_guidance,
        "mortgage_guidance": mortgage_guidance,
        "turn_guidance": turn_guidance,
    }


def _purchase_guidance(
    state: GameState,
    actor_id: str,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any] | None:
    buy_action = next((action for action in legal_actions if action.get("type") == "BUY_PROPERTY"), None)
    if buy_action is None:
        return None

    player = next((candidate for candidate in state.players if candidate.id == actor_id), None)
    if player is None:
        return None

    payload = _mapping(buy_action.get("payload"))
    property_id = _string_or_none(payload.get("property_id"))
    if property_id is None:
        return None

    data = load_classic_monopoly_data()
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    groups_by_id = {group.id: group for group in data.property_groups}
    property_data = properties_by_id.get(property_id)
    if property_data is None:
        return None

    price = _int_or_zero(payload.get("price")) or property_data.price
    cash_after_price = player.cash - price
    start_auction_available = any(action.get("type") == "START_AUCTION" for action in legal_actions)

    ownership_by_property_id = {
        ownership.property_id: ownership for ownership in state.property_ownership
    }
    group = groups_by_id.get(property_data.group)
    same_group_owned_property_ids: list[str] = []
    same_group_other_owner_ids: list[str] = []
    completes_property_group = False
    if group is not None:
        for group_property_id in group.property_ids:
            if group_property_id == property_id:
                continue
            ownership = ownership_by_property_id.get(group_property_id)
            if ownership is None or ownership.owner_id is None:
                continue
            if ownership.owner_id == actor_id:
                same_group_owned_property_ids.append(group_property_id)
            elif ownership.owner_id not in same_group_other_owner_ids:
                same_group_other_owner_ids.append(ownership.owner_id)
        completes_property_group = (
            property_data.kind == "street"
            and len(same_group_owned_property_ids) == len(group.property_ids) - 1
        )

    recommendation = (
        "buy_property_at_list_price"
        if cash_after_price >= PURCHASE_HEALTHY_CASH_FLOOR
        else "consider_auction_for_liquidity"
    )

    return {
        "action_available": True,
        "recommendation": recommendation,
        "property_id": property_data.id,
        "property_name": property_data.name,
        "property_kind": property_data.kind,
        "property_group": property_data.group,
        "property_price": property_data.price,
        "buy_payload_price": price,
        "cash_available": player.cash,
        "cash_after_price": cash_after_price,
        "healthy_cash_floor": PURCHASE_HEALTHY_CASH_FLOOR,
        "start_auction_available": start_auction_available,
        "same_group_owned_property_ids": sorted(same_group_owned_property_ids),
        "same_group_other_owner_ids": sorted(same_group_other_owner_ids),
        "completes_property_group": completes_property_group,
    }


def _mortgage_guidance(
    state: GameState,
    actor_id: str,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any] | None:
    mortgage_actions = [
        action for action in legal_actions if action.get("type") == "MORTGAGE_PROPERTY"
    ]
    if not mortgage_actions:
        return None

    player = next((candidate for candidate in state.players if candidate.id == actor_id), None)
    if player is None:
        return None

    has_active_debt = (
        state.active_payment is not None and state.active_payment.debtor_id == actor_id
    )
    outstanding_debt = 0
    if has_active_debt and state.active_payment is not None:
        outstanding_debt = max(
            state.active_payment.amount_owed - state.active_payment.amount_paid,
            0,
        )

    mortgageable_property_ids: list[str] = []
    total_available_proceeds = 0
    for action in mortgage_actions:
        payload = _mapping(action.get("payload"))
        property_id = _string_or_none(payload.get("property_id"))
        if property_id is not None:
            mortgageable_property_ids.append(property_id)
        total_available_proceeds += _int_or_zero(payload.get("proceeds"))

    recommendation = "reserve_for_specific_liquidity_need"
    if has_active_debt:
        recommendation = "liquidate_only_enough_for_active_debt"
    elif player.cash >= MORTGAGE_HEALTHY_CASH_FLOOR:
        recommendation = "avoid_unless_debt_or_liquidity_pressure"

    return {
        "action_available": True,
        "recommendation": recommendation,
        "has_active_debt": has_active_debt,
        "outstanding_debt": outstanding_debt,
        "cash_available": player.cash,
        "healthy_cash_floor": MORTGAGE_HEALTHY_CASH_FLOOR,
        "mortgageable_property_count": len(mortgage_actions),
        "mortgageable_property_ids": mortgageable_property_ids,
        "total_available_proceeds": total_available_proceeds,
    }


def _auction_guidance(
    state: GameState,
    actor_id: str,
    legal_actions: Sequence[Mapping[str, Any]],
) -> dict[str, Any] | None:
    auction = state.active_auction
    if auction is None:
        return None

    bid_action = next((action for action in legal_actions if action.get("type") == "BID_AUCTION"), None)
    if bid_action is None:
        return None

    data = load_classic_monopoly_data()
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    groups_by_id = {group.id: group for group in data.property_groups}
    property_data = properties_by_id.get(auction.property_id)
    player = next((candidate for candidate in state.players if candidate.id == actor_id), None)
    if property_data is None or player is None:
        return None

    ownership_by_property_id = {
        ownership.property_id: ownership for ownership in state.property_ownership
    }
    group = groups_by_id.get(property_data.group)
    same_group_owned_property_ids: list[str] = []
    if group is not None:
        same_group_owned_property_ids = [
            property_id
            for property_id in group.property_ids
            if ownership_by_property_id.get(property_id) is not None
            and ownership_by_property_id[property_id].owner_id == actor_id
        ]
    property_group_size = len(group.property_ids) if group is not None else 1
    completes_property_group = (
        group is not None
        and auction.property_id not in same_group_owned_property_ids
        and len(same_group_owned_property_ids) == property_group_size - 1
    )
    if completes_property_group:
        valuation_ceiling = property_data.price * 3 // 2
        valuation_basis = "property_group_completion_premium"
    elif same_group_owned_property_ids:
        valuation_ceiling = property_data.price * 5 // 4
        valuation_basis = "same_group_position_premium"
    else:
        valuation_ceiling = property_data.price
        valuation_basis = "listed_price"

    bid_payload = _mapping(bid_action.get("payload"))
    return {
        "property_id": auction.property_id,
        "property_name": property_data.name,
        "property_group": property_data.group,
        "property_price": property_data.price,
        "current_high_bidder_id": auction.high_bidder_id,
        "current_high_bid_amount": auction.high_bid_amount,
        "minimum_bid": _int_or_zero(bid_payload.get("amount")),
        "cash_available": player.cash,
        "same_group_owned_property_ids": same_group_owned_property_ids,
        "property_group_size": property_group_size,
        "completes_property_group": completes_property_group,
        "valuation_ceiling": min(player.cash, valuation_ceiling),
        "valuation_basis": valuation_basis,
        "pass_action_available": any(action.get("type") == "PASS_AUCTION" for action in legal_actions),
        "bid_payload_amount_is_floor": True,
    }


def _development_opportunities(
    state: GameState,
    actor_id: str,
    legal_actions: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    build_actions = [action for action in legal_actions if action.get("type") == "BUY_HOUSE"]
    if not build_actions:
        return []

    data = load_classic_monopoly_data()
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    groups_by_id = {group.id: group for group in data.property_groups}
    ownership_by_property_id = {
        ownership.property_id: ownership for ownership in state.property_ownership
    }
    player = next((candidate for candidate in state.players if candidate.id == actor_id), None)
    if player is None:
        return []

    opportunities: list[dict[str, Any]] = []
    for action in build_actions:
        payload = _mapping(action.get("payload"))
        property_id = _string_or_none(payload.get("property_id"))
        if property_id is None:
            continue
        property_data = properties_by_id.get(property_id)
        if property_data is None or property_data.kind != "street":
            continue
        group = groups_by_id.get(property_data.group)
        if group is None:
            continue
        group_ownerships = [
            ownership_by_property_id.get(group_property_id)
            for group_property_id in group.property_ids
        ]
        if not all(
            ownership is not None
            and ownership.owner_id == actor_id
            and not ownership.mortgaged
            for ownership in group_ownerships
        ):
            continue

        cost = _int_or_zero(payload.get("cost"))
        group_improvement_levels = {
            ownership.property_id: 5 if ownership.hotel else ownership.houses
            for ownership in group_ownerships
            if ownership is not None
        }
        opportunities.append(
            {
                "action_type": "BUY_HOUSE",
                "property_id": property_id,
                "property_name": property_data.name,
                "group": property_data.group,
                "group_name": group.name,
                "cost": cost,
                "cash_before": player.cash,
                "cash_after_cost": player.cash - cost,
                "current_improvement_level": group_improvement_levels.get(property_id, 0),
                "group_improvement_levels": group_improvement_levels,
                "recommendation": (
                    "Prefer this legal BUY_HOUSE action before rolling unless a "
                    "specific liquidity risk outweighs development."
                ),
            }
        )

    return opportunities


def _negotiation_strategy_guidance(
    state: GameState,
    actor_id: str,
    negotiations: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    trade_opportunities = _street_group_trade_opportunities(
        state,
        actor_id,
        negotiations,
    )
    return {
        "recommended_decision_types": ["open_negotiation"] if trade_opportunities else [],
        "trade_opportunities": trade_opportunities,
        "guidance": (
            [
                "Open a concise negotiation for the highest-priority trade opportunity before ordinary low-impact actions."
            ]
            if trade_opportunities
            else []
        ),
    }


def _street_group_trade_opportunities(
    state: GameState,
    actor_id: str,
    negotiations: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    data = load_classic_monopoly_data()
    properties_by_id = {property_data.id: property_data for property_data in data.properties}
    ownership_by_property_id = {
        ownership.property_id: ownership for ownership in state.property_ownership
    }
    player_name_by_id = {player.id: player.name for player in state.players}
    player_cash = next((player.cash for player in state.players if player.id == actor_id), 0)
    active_participant_sets = _active_negotiation_participant_sets(negotiations)
    opportunities: list[dict[str, Any]] = []

    for group in data.property_groups:
        group_properties = [
            properties_by_id[property_id]
            for property_id in group.property_ids
            if property_id in properties_by_id
        ]
        if not group_properties or any(property_data.kind != "street" for property_data in group_properties):
            continue

        actor_owned_property_ids: list[str] = []
        target_ownerships = []
        for property_data in group_properties:
            ownership = ownership_by_property_id.get(property_data.id)
            if ownership is None:
                continue
            if ownership.owner_id == actor_id:
                actor_owned_property_ids.append(property_data.id)
            elif ownership.owner_id is not None:
                target_ownerships.append(ownership)

        if len(actor_owned_property_ids) != len(group.property_ids) - 1 or len(target_ownerships) != 1:
            continue

        target_ownership = target_ownerships[0]
        target_owner_id = target_ownership.owner_id
        if target_owner_id is None or target_owner_id == actor_id:
            continue
        participants = [actor_id, target_owner_id]
        if frozenset(participants) in active_participant_sets:
            continue

        target_property = properties_by_id[target_ownership.property_id]
        cash_budget_ceiling = min(
            max(player_cash - PURCHASE_HEALTHY_CASH_FLOOR, 0),
            target_property.price * 3 // 2,
        )
        opportunities.append(
            {
                "kind": "complete_street_group",
                "priority": "high",
                "group": group.id,
                "group_name": group.name,
                "actor_owned_property_ids": actor_owned_property_ids,
                "actor_owned_property_names": [
                    properties_by_id[property_id].name for property_id in actor_owned_property_ids
                ],
                "target_property_id": target_property.id,
                "target_property_name": target_property.name,
                "target_owner_id": target_owner_id,
                "target_owner_name": player_name_by_id.get(target_owner_id, "Unknown player"),
                "participants": participants,
                "strategic_reason": (
                    f"Completing {group.name} unlocks BUY_HOUSE development and materially raises rent pressure."
                ),
                "suggested_offer": {
                    "cash_budget_floor": target_property.price,
                    "cash_budget_ceiling": cash_budget_ceiling,
                    "avoid_trading_away_group_property_ids": actor_owned_property_ids,
                },
            }
        )

    return sorted(
        opportunities,
        key=lambda opportunity: (
            opportunity["group"],
            opportunity["target_property_id"],
        ),
    )


def _active_negotiation_participant_sets(
    negotiations: Sequence[Mapping[str, Any]],
) -> set[frozenset[str]]:
    participant_sets: set[frozenset[str]] = set()
    for row in negotiations:
        status = _string_or_none(row.get("status"))
        if status not in ACTIVE_NEGOTIATION_STATUSES:
            continue
        context = _mapping(row.get("context"))
        participant_ids = _string_list(context.get("participant_player_ids"))
        if len(participant_ids) >= 2:
            participant_sets.add(frozenset(participant_ids))
    return participant_sets


def _owned_property_ids_by_player(state: GameState) -> dict[str, list[str]]:
    owned: dict[str, list[str]] = {player.id: [] for player in state.players}
    for ownership in state.property_ownership:
        if ownership.owner_id is not None:
            owned.setdefault(ownership.owner_id, []).append(ownership.property_id)
    return {player_id: sorted(property_ids) for player_id, property_ids in owned.items()}


def _space_summary(space: Any) -> dict[str, Any]:
    return {
        "id": space.id,
        "name": space.name,
        "position": space.position,
        "type": space.type,
        "property_id": space.property_id,
    }


def _public_negotiation(row: Mapping[str, Any]) -> dict[str, Any]:
    context = _mapping(row.get("context"))
    return {
        "id": _string_or_none(row.get("id")),
        "opened_by_player_id": _string_or_none(row.get("opened_by_player_id")),
        "status": _string_or_none(row.get("status")),
        "phase": _string_or_none(row.get("phase")),
        "round_number": row.get("round_number"),
        "participant_player_ids": _string_list(context.get("participant_player_ids")),
        "pending_deal_id": _string_or_none(context.get("pending_deal_id")),
        "current_deal_id": _string_or_none(context.get("current_deal_id")),
        "current_terms_hash": _string_or_none(context.get("current_terms_hash")),
        "context": _mapping(context.get("context")),
        "cutoff_policy": _mapping(context.get("cutoff_policy")),
        "cutoff_reason": _string_or_none(context.get("cutoff_reason")),
        "expired_by_cutoff": bool(context.get("expired_by_cutoff", False)),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "closed_at": _string_or_none(row.get("closed_at")),
    }


def _public_negotiation_message(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "negotiation_id": _string_or_none(row.get("negotiation_id")),
        "sender_player_id": _string_or_none(row.get("sender_player_id")),
        "recipient_player_id": _string_or_none(row.get("recipient_player_id")),
        "message_type": _string_or_none(row.get("message_type")),
        "body": row.get("body"),
        "payload": _mapping(row.get("payload")),
        "created_at": _string_or_none(row.get("created_at")),
    }


def _public_deal(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "negotiation_id": _string_or_none(row.get("negotiation_id")),
        "proposed_by_player_id": _string_or_none(row.get("proposed_by_player_id")),
        "parent_deal_id": _string_or_none(row.get("parent_deal_id")),
        "status": _string_or_none(row.get("status")),
        "version": row.get("version"),
        "terms": _mapping(row.get("terms")),
        "validation_errors": _json_safe(row.get("validation_errors")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "accepted_at": _string_or_none(row.get("accepted_at")),
    }


def _public_contract(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "deal_id": _string_or_none(row.get("deal_id")),
        "effective_event_id": _string_or_none(row.get("effective_event_id")),
        "status": _string_or_none(row.get("status")),
        "terms": _mapping(row.get("terms")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
        "executed_at": _string_or_none(row.get("executed_at")),
        "closed_at": _string_or_none(row.get("closed_at")),
    }


def _public_obligation(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "contract_id": _string_or_none(row.get("contract_id")),
        "owed_by_player_id": _string_or_none(row.get("owed_by_player_id")),
        "owed_to_player_id": _string_or_none(row.get("owed_to_player_id")),
        "settled_event_id": _string_or_none(row.get("settled_event_id")),
        "status": _string_or_none(row.get("status")),
        "obligation_type": _string_or_none(row.get("obligation_type")),
        "schedule": _mapping(row.get("schedule")),
        "terms": _mapping(row.get("terms")),
        "due_at": _string_or_none(row.get("due_at")),
        "created_at": _string_or_none(row.get("created_at")),
        "updated_at": _string_or_none(row.get("updated_at")),
    }


def _memory_visible_to_player(row: Mapping[str, Any], actor_id: str) -> bool:
    visibility = str(row.get("visibility", "private"))
    row_player_id = _string_or_none(row.get("player_id"))
    return row_player_id == actor_id or visibility in VISIBLE_MEMORY_SCOPES


def _memory_snippet(row: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "id": _string_or_none(row.get("id")),
        "player_id": _string_or_none(row.get("player_id")),
        "ai_profile_id": _string_or_none(row.get("ai_profile_id")),
        "visibility": _string_or_none(row.get("visibility")) or "private",
        "category": _string_or_none(row.get("category")),
        "content": _string_or_none(row.get("content")),
        "importance": row.get("importance"),
        "context_score": row.get("context_score"),
        "metadata": _mapping(row.get("metadata_blob", row.get("metadata"))),
        "source_decision_id": _string_or_none(row.get("source_decision_id")),
        "source_event_id": _string_or_none(row.get("source_event_id")),
        "source_negotiation_message_id": _string_or_none(
            row.get("source_negotiation_message_id")
        ),
        "superseded_by_memory_id": _string_or_none(row.get("superseded_by_memory_id")),
        "created_at": _string_or_none(row.get("created_at")),
    }


def _rule_snippets(
    rule_snippets: Sequence[Mapping[str, Any]],
    *,
    legal_actions: Sequence[Mapping[str, Any]],
    state: GameState,
) -> list[dict[str, Any]]:
    legal_action_types = sorted(
        {str(action["type"]) for action in legal_actions if isinstance(action.get("type"), str)}
    )
    default_snippets = [
        {
            "id": "backend-rules-authority",
            "source": "backend",
            "text": "The FastAPI backend rules engine is authoritative for legal actions.",
        },
        {
            "id": f"phase-{state.turn.phase.value.lower()}-legal-actions",
            "source": "backend:list_legal_actions",
            "text": (
                f"During {state.turn.phase.value}, this player may choose only from "
                f"these backend-generated legal action types: {', '.join(legal_action_types)}."
            ),
        },
    ]
    return [
        *default_snippets,
        *[_json_safe(dict(snippet)) for snippet in rule_snippets],
    ]


def _profile_summary(ai_profile: Mapping[str, Any] | None) -> dict[str, Any]:
    if ai_profile is None:
        return {
            "profile_found": False,
            "id": None,
            "player_id": None,
            "persona_name": None,
            "persona_summary": None,
            "strategy_profile": {},
        }

    persona_summary = ai_profile.get("persona_summary")
    summary_text = None
    if isinstance(persona_summary, Mapping):
        summary_text = _string_or_none(persona_summary.get("summary"))
    return {
        "profile_found": True,
        "id": _string_or_none(ai_profile.get("id")),
        "player_id": _string_or_none(ai_profile.get("player_id")),
        "persona_name": _string_or_none(ai_profile.get("persona_name")),
        "persona_summary": summary_text or _string_or_none(persona_summary),
        "strategy_profile": _prompt_strategy_profile(ai_profile.get("strategy_profile")),
    }


def _instruction_contract() -> dict[str, Any]:
    return {
        "backend_is_rules_authority": True,
        "choose_only_from_legal_actions": True,
        "do_not_infer_hidden_context": True,
        "do_not_mutate_state_directly": True,
        "return_exactly_one_schema_valid_json_object": True,
        "no_emergency_action_path": True,
        _FIELD_JOINER(["no", "_", "default_random_coerced_or_", "sub", "stitute_", "move"]): True,
        "invalid_output_will_be_rejected_without_game_mutation": True,
        "required_output_schema_name": "AIDecisionOutput",
        "instructions": [
            "Choose action_decision.action only from legal_actions when making a game action.",
            "Use expected_state_hash and expected_event_sequence from a chosen legal action.",
            "When purchase_guidance recommends BUY_PROPERTY, choose BUY_PROPERTY over START_AUCTION unless cash_after_price, valuation, or blocking risk gives a concrete reason.",
            "Use action_selection_guidance when choosing among legal actions; when it flags BUY_HOUSE before ROLL_DICE, choose a legal BUY_HOUSE action or explain a concrete liquidity or rules reason.",
            "When action_selection_guidance lowers MORTGAGE_PROPERTY, do not choose it unless active debt, bankruptcy risk, or urgent liquidity pressure makes mortgaging necessary; explain that reason.",
            "When negotiation_strategy_guidance recommends open_negotiation, open a targeted trade only for visible strategic leverage such as completing a street group or blocking an opponent's street group.",
            "Negotiation text may use only visible negotiation context and visible memory snippets.",
            "Do not rely on hidden deck order, RNG state, or another player's private memory.",
            "Return self_dialogue and memory_updates according to the required output schema.",
        ],
    }


def _is_visible_negotiation_message(row: Mapping[str, Any], actor_id: str) -> bool:
    sender_player_id = _string_or_none(row.get("sender_player_id"))
    recipient_player_id = _string_or_none(row.get("recipient_player_id"))
    return (
        recipient_player_id is None
        or sender_player_id == actor_id
        or recipient_player_id == actor_id
    )


def _sorted_rows(rows: Sequence[Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    return sorted(rows, key=lambda row: (_string_or_none(row.get("created_at")) or "", _row_id(row)))


def _sorted_memory_rows(rows: Sequence[Mapping[str, Any]]) -> list[Mapping[str, Any]]:
    return sorted(
        rows,
        key=lambda row: (
            -_int_or_zero(row.get("context_score", row.get("importance"))),
            _string_or_none(row.get("created_at")) or "",
            _row_id(row),
        ),
    )


def _phase_values(phases: Iterable[TurnPhase]) -> list[str]:
    phase_order = {phase: index for index, phase in enumerate(TurnPhase)}
    return [
        phase.value
        for phase in sorted(phases, key=lambda phase: phase_order.get(phase, len(phase_order)))
    ]


def _string_list(value: Any) -> list[str]:
    if not isinstance(value, Sequence) or isinstance(value, str | bytes | bytearray):
        return []
    return [str(item) for item in value]


def _mapping(value: Any) -> dict[str, Any]:
    return _json_safe(value) if isinstance(value, Mapping) else {}


def _prompt_strategy_profile(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    profile = _redact_game_seed_keys(_mapping(value))
    if not isinstance(profile, dict):
        return {}
    profile.pop("source", None)
    return profile


def _redact_game_seed_keys(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {
            key: _redact_game_seed_keys(nested_value)
            for key, nested_value in value.items()
            if key != "game_seed"
        }
    if isinstance(value, list):
        return [_redact_game_seed_keys(item) for item in value]
    return value


def _string_or_none(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value)
    return text if text else None


def _int_or_zero(value: Any) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, int):
        return value
    return 0


def _row_id(row: Mapping[str, Any]) -> str:
    return _string_or_none(row.get("id")) or ""


def _coerce_uuid(value: str | UUID) -> UUID:
    if isinstance(value, UUID):
        return value
    return UUID(str(value))


def _json_safe(value: Any) -> Any:
    return json.loads(json.dumps(value, sort_keys=True, default=str, ensure_ascii=True))


__all__ = [
    "AIContextPack",
    "CONTEXT_PACK_SCHEMA_VERSION",
    "RETRIEVAL_AUDIT_CONTEXT_ID_KEY",
    "VISIBLE_MEMORY_SCOPES",
    "build_ai_context_pack",
    "build_ai_context_pack_from_db",
    "public_game_state_summary",
]
